SAV/SAV_Inventory.cs
SAV/SAV_SuperTrain.cs

Hello again, I have added a fix for an issue that occurs when using Mono in which calling add on a DataGridViewRowCollection would place the (zeroth row, zeroth cell) cell into edit mode and set it's Edited Value to empty string. Therefore later when the cell is populated with a value in this line
`dataGridView1.Rows[i].Cells[0].Value = itemarr[itemarrayval];`
the Edited Value is not updated to point to the new value for the name of the item. The fix is to move the newly populated empty cell out of edit mode.
Long story short this change is to fix the issue with the first item name in the Inventory Item showing up as empty string on Mono.
I have fully tested this change on Windows and Linux and verified that it causes no issues especially on Windows.
The second change is to fix the issue …

Fix for a Mono specific issue when editing the inventory. Also fixed a general issue with the Super Training dialog

---

SAV/SAV_Trainer.cs

Hello kwsch, I have added a fix for an uncaught system format exception in the SAV_Trainer::change255 function due to the text box containing trailing underscores.

Fix for uncaught numeric parse exception

---

SAV/SAV_Inventory.Designer.cs

Hello again, I made a change to the inventory editor to fix an issue when using PKHeX in Mono in which the controls would get cut-off horizontally. The change was to increase the maximum width of inventory editor.
This change does not affect running on Windows as Windows is able to fit in the 350 pixel width.
This is how it looks on Windows before and after
And this is how it looks on Linux before and after

Updating Inventory Editor width for Mono

---

PKX/f1-Main.cs

This bug occurred via switching from "Australia" to "Austria" while selecting "Vorarlberg".
It throws an ArgumentException and this is the fix I used while working on this: http://projectpokemon.org/forums/showthread.php?44994-Mass-Editor-for-all-PKHeX-supported-files

Fixing a bug with the Country Sub Region selection

---

PKX/f1-Main.cs

When dumping all boxes to a folder, prompt user if he wants to create a folder for each box instead of dumping all pk6 files at the same folder.

Allow dumping all pk6 files to separate box folders

---

PKX/f3-MemoryAmie.cs

After saving changes in the Memories Editor, the pokemon memory feeling will always be saved as 0. This is because CB_OTFeel and CB_CTFeel are not bound to a datasource in getLangStrings(), and thus SelectedValue will always return null, and Util.GetIndex will always return 0. Fix is to use SelectedIndex instead.

Pokemon feelings not being saved correctly after closing dialog box

---

Misc/PKX.cs
PKX/f1-Main.cs

Pokemon originating from Gen III & IV had their nature determined by their PID. Since there is no way in-game to modify a Pokemon's nature, Gen <=IV Pokemon PIDs should be generated to take nature into consideration, and not just any random value will may fail the mod 25 calculation.
Gen VI games will happily accept previous gen Pokemon will illegal PID/nature combination, but such a Pokemon theoretically does not exist.

For Gen III & IV Pokemon, generate PIDs to ensure legal nature

---

SAV/SAV_PokedexXY.cs

Missing line copied from ORAS (offsets are the same).

Fix Pokedex form bitflags not saved in XY

---

PKX/f1-Main.cs

Toggling of the daycare display previously toggled DaycareIndex only in Main but not SAV. Deposited Pokemon in the Battle Resort daycare were still displayed correctly, but they would appear as unoccupied and with gained EXP 0.

ORAS: fix incorrect display if only daycare 1 is empty

---

PKX/f1-Main.cs

The OS seems to remember the last path used in file dialogs even between launches of the application.
This gets rid of the "no disk in drive" error if a user last performs any file operation on a removable drive, quits PKHeX, ejects the drive, re-launches the application and attempts to use the open file dialog.

Explicitly set InitialDirectory when creating new OpenFileDialog

---

Misc/Util.cs

This PR addresses a Mono-specific regression introduced in 8469d04.
Due to Mono bug [12241](https://bugzilla.xamarin.com/show_bug.cgi?id=12241), when run in a Mono environment, all MaskedTextBoxes return underscores in their Text property and causing FormatException to be thrown.
I am not sure about this approach to addressing upstream bugs, but Mono users are completely unable to launch the program without this workaround, and that bug doesn't look like it will be fixed any time soon.

Trim underscores in Util.ToInt32 and Util.ToUInt32

---

Legality/Checks.cs

As commit message says. Lack of return here made some legal event Pokémons (those that match only one Wonder Card, like ORAS Shiny Beldum) show up as illegal.

Fix Legality Check for some Wonder Cards

---

Legality/Checks.cs
Legality/Core.cs
Legality/Tables.cs

This commit also adds one new method `Legality.isValidMachineMove` to the legality core, which was mostly copied from `getValidMoves`.
If I remember correctly, there is no Pokemon out there yet with different TM/HM learnsets across formes, so that method could be trimmed down further, or at least until S/M introduces such a species.

Add legality checks for HM-specific memories

---

PKX/f1-Main.cs

An oddity will otherwise force the smaller index (Kalos') to be selected instead.

Distinguish between Leagues of both regions in location dropdown

---

Legality/Checks.cs
Legality/Core.cs

{0} used {2} at {1}'s instruction, but it had no effect
The Move Deleter that {0} met through {1} made it forget {2}
For this to work properly with Smeargle we must check only if the specified move is valid as Sketch method because getValidMoves will only return Sketch as the one Smeargle can learn through level and through relearn.

Checks for memories 16/48 and fix Smeargle exception

---

Legality/Analysis.cs
Legality/Checks.cs

During first setup depending of the region of the 3DS it only allows certain countries to be selected, this values all also applied on the savefile and on Pokemon as well when they're obtained so per example having a Pokemon with a 3DS region set to Japan but country as Spain is illegal.
Actually some events are region locked, the ones distributed through codes or Network, local wireless distributions are region-free, so in the future the WC6 checking should also include checking if the 3DS region set for that Pokemon is legal based on how the event was distributed.
Also check for memorie number 49 that refers to remembering a move. This actually flagged one of my Pokemon, A Torterra that remembers relearning Electro Ball lol
Also idk if you saw my post on the forum regarding the fishing …

Geolocation and memory 49 checks

---

SAV/SAV_BoxLayout.Designer.cs

In the box layout editor, the textbox mask for the first unlocked BG flag is "00", which led to unexpected truncation.
This leads to a side effect in-game in which the player can select only the first 4 out of the available 8 special PC wallpapers. (the "next" option will be hidden by the game)
For existing savefiles affected by this issue, the correct flag for post-Elite 4 wallpaper unlock is "131".

Fix truncation of box unlocked BG flags

---

Legality/Checks.cs

There's no point of saying a Landorus, per example, is missing Fissure, Block, Mud Shot and Rock Romb as relearn moves just because it was hatched from an egg because to start with the species cannot be hatched.

Don't check base moves if the pkm can't be hatched

---

Legality/Checks.cs

This will flag Pokemon with this memory, but did not hatch from an egg.
Also, a second commit that fixes a typo in verifyHTMemory.

Checks for OT memory 2: hatched from an egg

---

Legality/Checks.cs

Second generation starters are legal with third generation introduced balls because you can catch their second stage on Pokemon Colosseum, but since back then Hidden Abilities didn't exist they're restricted to normal balls only.
Other balls are checked already but this ones weren't flagged as illegal.

Fix third gen balls on second gen starters with HA

---

Legality/Checks.cs

Move all memory checks pertaining to OT memory from verifyHistory to verifyOTMemory, to avoid flagging WC6s with defined OT memories.
Also, clarifies the check output for verifyHistory.

Legality: separate memory checks from history checks

---

Saves/SAV4.cs
Saves/SAV5.cs
Saves/SAV6.cs
Saves/SaveUtil.cs

These changes make it possible for external applications (like [Sky Editor](https://github.com/evandixon/SkyEditor.SaveEditor.PKHeXIntegration)) to use PKHeX as a class library.
Notable Changes:
- SaveUtil is no longer marked internal.
- SAV4, SAV5, and SAV6 initialize Footer so that Write can be called without setting it externally and without a NullReferenceException.
- Replaced certain integer results in SaveUtil with enums to improve readability.
Using these changes I successfully changed my OT through Sky Editor, using PKHeX as a class library.

Enable Use as Class Library

---

Util/DataUtil.cs

Allows external programs to get string lists for use with displaying lists of PKHeX objects.
Example usage:
http://www.skyeditor.org/2016/07/status-update-pkhex-integration.html

Made internal PKHeX.Util.getStringList functions public

---

MainWindow/Main.Designer.cs
MainWindow/Main.cs

It required subscribing to many more events, but I've improved the way drag and drop is initiated by having it only create the temporary file when you hold left mouse down and then proceed to move the mouse. With the changes it will be easier to write event handlers for mouse clicks that will do different tasks. I'm thinking of proposing changes to how box controls work.
Also I changed it so it prevents drag and drop of blank pokemon from slots previously held by dragged pokemon.

Improved the way drag and drop is initiated

---

PKHeX/MainWindow/Main.cs
PKHeX/PKHeX.csproj

Reverted ClickOnce deployment code due to Mono and Wine not supporting it.
Should fix issue #161
I know I could just push this directly into master, but on a widely used application like this, I think it improves code quality if others have the opportunity to review my changes, just in case I missed something.

Reverted ClickOnce deployment code due to Mono and Wine not supporting it.

---

PKHeX/MysteryGifts/PGF.cs
PKHeX/MysteryGifts/WC6.cs
PKHeX/PKM/PKM.cs
PKHeX/Util/DateUtil.cs
Tests/PKHeX.Tests/PKM/PKMTests.cs
Tests/PKHeX.Tests/Util/DateUtilTests.cs

So I tried out this Pokemon using my latest code, and things broke (live version doesn't have the date refactoring yet):
http://pkmdb.skyeditor.org/Pokemon/Details/c29e5bf0-a63c-4c61-a949-f21c07f72c18
Turns out DateUtil was crashing because it incorrectly got `0` instead of `2000`, so I fixed that.  I also fixed it crashing when it gets a zero year.

Fixed crash in DateUtil when Year is 0

---

PKHeX/PKM/PKM.cs

With further checking the PKMs that were migrated from PK4 to PK5, I noticed that when the conversion removed HM moves, the `FixMoves()` call was not shifting the moves up correctly. I also noticed that if the HM move was in the last position, the PP value for it would not be cleared by the `FixMoves()` call.
Some examples to Illustrate what I mean:
A Pokemon with:
1. Cut 30 PP --> Removed on conversion
2. Crunch 15 PP
3. Giga Drain 10 PP
4. Frenzy Plant 5 PP
Would result in:
1. Crunch 15 PP
2. ---
3. Giga Drain 10 PP
4. Frenzy Plant 5 PP
Because the code checks for moving first from below, it simply moved the second move to the first slot and then it didn't check any further.
I think the fix is a quick fix that can be done better, but this does the trick.

Fix reorder moves and clear PP values for empty moves.

---

PKHeX/Subforms/Save Editors/SAV_EventFlags.cs

var mtb = new NumericUpDown
{
Maximum = short.MaxValue,
Minimum = short.MinValue,
Value = Constants[num[i]],
In the above code snippet, Constants[num[i]] is a ushort, while the min and max of the NumericUpDown are being set to the min and max of short.  This commit fixes that, and by extension, #196.
I'm opening a PR instead of directly pushing both because that's what I'm in the habit of doing now, but also to give others a chance to decide whether or not Constants[num[i]] should really be a short.  I chose to make the range a ushort since that's the smaller/safer of the two possible solutions I see.

Changed min and max of NumericUpDown from short to ushort

---

PKHeX/Properties/Resources.resx

Mono on Linux needs to have all ressources files to respect filename case (or use MONO_IOMAP=all)

Fix file path case (Linux is case sensitive)

---

PKHeX/Saves/SaveUtil.cs

Fixes at least part of the issue in the latest commit described here:
https://projectpokemon.org/forums/showthread.php?50222-Gen-IV-Encounters-from-Platinum-DeSmuMe-dsv

Fixed file size being altered when loading a dsv save

---

PKHeX/Saves/SAV1.cs
PKHeX/Saves/SAV2.cs
PKHeX/Saves/SAV3.cs
PKHeX/Saves/SAV3Colosseum.cs
PKHeX/Saves/SAV3RSBox.cs
PKHeX/Saves/SAV3XD.cs
PKHeX/Saves/SAV4.cs
PKHeX/Saves/SAV5.cs

From PP IRC:
```
<Sylveon700> when saving ds games you use dsv and pkhex saves as dsv
<Sylveon700> but save sa1 it will rename the file .sa1.sav
<Sylveon700> i feel nobody understands me
```
This pull request should help fix exactly that issue.

Added "All Files" to save filters

---

PKHeX/MainWindow/Main.Designer.cs
PKHeX/MainWindow/Main.cs

Adds feature described in issue #325.
This PR adds a dialog asking for confirmation if someone tries to close the form when there's unsaved changes.  Saving through `clickExportSAV` marks the current save as no longer modified, and will not display the dialog.  I'm unsure if saving the backup with `clickExportSAVBAK` should mark the save as not modified, but it looks fine as-is.

Added warning when closing PKHeX with unsaved changes

---

PKHeX/Saves/Substructures/Inventory.cs

I don't have a 7th gen save ready, so this is completely untested, but as long as the research in the comments is correct, I see no reason why this won't work.

Possible fix for issue #347 (999 item count becomes 39)

---

PKHeX/Subforms/frmReport.cs

With the addition of Generation 7, this "down-converts" these properties to the previous generation, and are incompatible. It should be safe to use the native properties' ToString() functions to do this job.
If not, then it should be fixed there - it shouldn't be PK6's job to handle data from other generations.

Don't cast 5+ string properties as version 6

---

PKHeX/Subforms/Save Editors/Gen6/SAV_BoxLayout.cs

Should fix issue #415 
The form itself should now support generations 4-7, although Gen 5 doesn't show the button to open this form.  The [wallpaper names](http://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_Storage_System#Generation_V) are the same, so once proper support is introduced, they should not have to be adjusted.

Fixed crash when opening SAV_BoxLayout with Gen 4 save

---

PKHeX/Legality/Checks.cs

Pokemon Species 731 is Pikipek and is Valid in Apricorn Ball
So >= 731 or > 730 is a valid check.

Invalid Check for Apricorn ball

---

PKHeX.sln
PKHeX/PKHeX.csproj
README.md

Renamed build configurations to clarify usage (hopefully avoiding misconceptions like in #618).  Also added the README to the solution (so it can be easily modified from within VS) and modified it to briefly describe when to use each build configuration.
Commits 95501698175f87dd719af235a30aba5181fead0f and fcc77fcf54f79950656be8d86a03bfe37c65a3f7 from julroy67's fork can be adapted to apply only when Mono-Debug or Mono-Release is the active configuration, although depending on the exact implementation, a MONO compiler constant may need to be defined.

Build Configuration Clarification

---

PKHeX/PKHeX.csproj

Also defined MONO compiler constant for future use in Mono builds
Team city mono build definition updated to zip /PKHeX/bin/Mono-Release/ while the .Net definition still zips /PKHeX/bin/Release/

Updated build directories

---

PKHeX/Saves/SAV7.cs
PKHeX/Subforms/Save Editors/Gen7/SAV_Trainer7.Designer.cs
PKHeX/Subforms/Save Editors/Gen7/SAV_Trainer7.cs

This PR attempts to fix the bug described [here](https://projectpokemon.org/forums/forums/topic/39557-error-on-pkhex-trying-to-edit-trainer-info-sun-and-moon/), but also fixed an error opening the trainer editor with the default blank save.
The changes:
- **Refactored LastSavedDate** - improves usage IMO and fixes a crash when opeining the trainer editor with the default blank save, since both the year and month were 0.
- **Extended the MinDate for HOF and Adventure Started** - What if HOFSeconds or AdventureStartedSeconds were negative?  That could result in the original bug report.  By my calculations, Integer.MinValue seconds results in the year 1932, which is the new min year (although now that I think about it I didn't consider month or day).
These changes have not been tested with a …

Fix Gen 7 Dates

---

PKHeX/MainWindow/Main.cs

[ddhelmet posted](https://projectpokemon.org/forums/files/file/1-pkhex/?tab=comments#comment-28):
```
Can it remember the last folder you took the save file from? It's a minor thing but would help me a lot
```
I'd like this too.  The default behavior of the OpenFileDialog is to do this, but PKHeX was doing its own stuff, resetting the directory _every single time_.
This PR will remove most of the stuff changing the OpenFileDialog initial directory, leaving auto-detecting the save file, in favor of the default dialog behavior of always using the previous last directory a file was opened from.  It also tweaks the default filter to allow all _supported_ files (main, sav, bin pk_, and ekx) instead of defaulting to All Files.

Simplified OpenFileDialog logic

---

PKHeX/PKHeX.csproj
PKHeX/PKM/PKX.cs

Only affects Mono-Debug and Mono-Release build configurations
Should resolve #618
May re-open #444 in Mono only
Briefly tested in an Ubuntu VM.  The current master branch failed to build and this branch appeared to work fine.  When running both using Wine, the Nickname and OT textboxes' characters were invisible.  I was unable to run the compiled version from my build server directly, and I'm not sure if it's a configuration error on Team City or a bad setup on my VM.

Contitionally add mono fix from #440

---

PKHeX.WinForms/PKHeX.WinForms.csproj
PKHeX.sln

Since the solution level one didn't build the dependencies, and the project level one built as x86 anyway

Removed "Any CPU" build configuration

---

PKHeX/Saves/SAV4.cs

0x12300 is the length, not the end offset. 0x21A00 = 0xF700 + 0x12300

Fix HGSS checksum offset

---

PKHeX/PKM/PKX.cs

The iterator in the for loop is executed only at the end of each iteration; this changes the comparison operator to avoid premature termination of the list at "pk6".

Fix acceptable PKX file extensions being off by one

---

PKHeX.WinForms/Subforms/Save Editors/SAV_Inventory.cs

Passing a height of 0 lets the TabControl dissapear, making it
impossible to switch tabs between different pouches.
To fix this, use the same approach as for the width and pass the height
of the first icon.
----
I can only test this on Linux, but I hope this issue isn't Linux-specific.

Fix tabs for bag pouches not showing on Linux/Mono

---

PKHeX/Legality/Checks.cs
PKHeX/Legality/Core.cs
PKHeX/Legality/Structures/EvolutionTree.cs

Modified the get lineage function to do not include preevolutions from generations above the source game of the pokemon.
This will work with gen 1 vc legal analisys but also it can be used in the future with gen 2 vc or other past gen
Example a gen 3 Snorlax wont return Munchlax in its lineage, nor a gen 1 vc raichu include pichu but gen 4 to 7 Snorlax and gen 2 vc and gen 3 to 7 raichu will include both Muchlax and Pichu

Get lineage using the source generation of the pokemon

---

PKHeX.WinForms/Program.cs

[This post](https://projectpokemon.org/forums/forums/topic/39971-is-wine-mac-os-x-even-able-to-detect-the-dll-file/) got me thinking... Is the error message really the fault of Wine?  It's possible, but the FileNotFound exception could really have come from anywhere in Main's constructor, which does all the things, including searching for potential saves.  In the past, there have been errors related to that, so there's no telling what the FileNotFound exception is really about.  This PR fixes that: if a FileNotFound exception is thrown, the target site is examined.  If it comes from StartPKHeX, then it means PKHeX.Core.dll could not be  loaded.  If it comes from Main's constructor (like if you put `throw new FileNotFoundException();` in the first line), then it's due to something else, in …

Made FileNotFoundException check more specific

---

Tests/PKHeX.Tests/PKM/PKMTests.cs

DateTime.UtcNow is considerably faster than DateTime.Now, and since this
value isn't used for actual game purposes, we can take advantage of it.

Tests: Use DateTime.UtcNow for test cases

---

PKHeX/Resources/text/es/text_Items_es.txt

Because 'ningún objeto' means 'no object', and it is used for moves too.

Correct translation for 'None' in Spanish.

---

PKHeX/PKHeX.Core.csproj

Creating a nuget package with TC failed because it couldn't find bin\x86\Release, when it should have looked in bin\Release.
After this change, a [nuget package](http://teamcity.projectpokemon.org/repository/download/PKHeX_BuildWindows/886:id/PKHeX.Core.1.0.1845.nupkg) was successfully created.

Changed default platform configuration for PKHeX.Core

---

PKHeX.WinForms/Program.cs

GetFrameworkVersion() throws an System.NullReferenceException since
there is no Registry on non-windows systems.
Fixed by checking the OS under which the program runs. If it's not
Windows, check the CLR Version instead of querying the (non-existant)
registry.

Add Framework check for non-windows OS

---

.gitignore
PKHeX/Legality/Analysis.cs
PKHeX/Legality/Checks.cs
PKHeX/Legality/Core.cs
PKHeX/Legality/Structures/DexLevel.cs
PKHeX/Legality/Structures/EvolutionTree.cs
PKHeX/Legality/Tables1.cs
PKHeX/Legality/Tables2.cs
PKHeX/Legality/Tables3.cs
PKHeX/Legality/Tables4.cs
PKHeX/Legality/Tables5.cs
PKHeX/PKM/PKM.cs

4 months ago i started to create files to help making past generation legal checks, the levelup, eggmoves and tmhm tables.
Back then it can yet be used because PKHeX was not ready.
Now with the last refactors made to the program I have resumed the extraction and i have also the encounter tables for gen 3 and 4. When i complete the extraction of encounters for gen 5 and evolution tables for gen 3 to 5 i will make a pull request to include it in PKHeX
For now i made some tweaks to the legalliy checks that would make more easy to start those past gen legal chechks.
The most important one is to generate different evolution chain arrays depending on the generation, to allow for a given pokemon to know the evolution chain across all the generation that it has inhabited, chaind that can be …

Past generations legallity tweaks

---

PKHeX/Legality/Checks.cs
PKHeX/Legality/Core.cs

Three changes:
getTutorMoves: Add parameter to filter by generation, because this function is called from a getMoves that is already filtering by generation. This avoid getMoves to return tutor moves for a generation different that the one filtered
getMoves: Remove moves above Max Moves in gen 1 when the function is using a format 1 pokemon and generation 2, a tradeback pokemon. Any gen 1 pokemon can be traded to gen 2 and learns moves from gen 2 learnset and then be traded again to gen 1 but only with moves that exists in gen 1
getValidMoves main function: This function is called three times from verifyMoves() to return 3 list with moves from level up, tmhm and tutor but every level up moves is included in all lists because the main function is not filtering by level up like tutor and …

Some small tweaks in get moves functions

---

PKHeX/Legality/Core.cs

A fix for a mistake in the last pull request i made.
getTutorMoves is using TypeTutor6 in generation is 7 when it should use TypeTutor7

Fix getTutorMoves from gen 7

---

PKHeX.WinForms/PKHeX.WinForms.csproj
PKHeX.sln
PKHeX/PKHeX.Core.csproj

ClickOnce needs a special setting not required by other builds (NoWin32Manifest).  Other builds do not need ClickOnce's System.Deployment.  Now, only the ClickOnce build configuration uses System.Deployment and no other configuration knows anything about it.
The super-secret dev clickonce has been updated to the results of this branch, but automatic uploads are not currently enabled.  The build results of the Team City build configuration can be seen by creating an account and asking me for access.

Made clickonce less intrusive to normal builds

---

PKHeX/Legality/Tables7.cs

Mewtwonite X and Mewtwonite Y were released today via worldwide serial code "M2DESCENT".

Remove legality checks on Mewtwonite X/Y

---

PKHeX/Legality/Core.cs
PKHeX/Legality/Structures/EncounterArea.cs
PKHeX/Legality/Structures/EncounterStatic.cs
PKHeX/Legality/Tables3.cs
PKHeX/Legality/Tables4.cs

- Gen 3 Swarm slots
- Added locations to gen 3 roaming static encounters
- Added egg location to gen 3 gift eggs and adapted encounter legal analysis, only unhatched gen 3 eggs can be differentiated from normal gen 3 eggs, if hatched assume normal egg for analysis purpose. In case of pokemon that can have special egg moves we can not know what king of egg was and we should check for both possible range of valid moves without mixing, egg moves and event egg moves
- Move gen 4 swarm encounter to encounter slot instead of encounter static. Also changed the data to hardcode only location and species id, levels can be loaded from normal encounters raw data because swarm slots replace slots 0 and 1

More Gen 3 and 4 Encounters

---

PKHeX/Legality/Core.cs
PKHeX/Legality/Tables3.cs
PKHeX/Legality/Tables4.cs

Get tutor moves for gen 3 and 4 pokemon, including special tutors
Filter deoxys gen 3 level moves by form
Remove HMs in gen 3 and 4 when transfered to another generation, even if gen 3 HMs are not added some pokemon can learn HMs by leveling up
Defog and Whirlpoll are not removed because a pokemon can be transfered to gen 5 learning only one, should be analyzed that a pokemon in gen 5 with both moves is illegal

Complete gen 3 and 4 tutor moves

---

PKHeX/Legality/Core.cs
PKHeX/Legality/Tables2.cs
PKHeX/PKM/PK2.cs
PKHeX/PKM/PKM.cs

Pokemon from gen 2 can have met location if they are caught in crystal.
It can be deduce a pokemon in format 2 with met location was captured in crystal.
A pokemon in format 2 without met location if is an species that cant be tradeback to gen 1 (like totodile) was captured in gold and silver.
To improve gen 2 legal analysis static encounters tables and encounter areas tables are loaded with those 3 possible origins, crystal, gold/silver or any gen 2 game.
A pokemon will use one of these 3 tables for encounter areas and static encouinters. Also if is from crystal met location and met level will be take into account to determine if the pokemon is legal

Gen 2 filter encounter location when with crystal met location

---

PKHeX/Legality/Core.cs
PKHeX/Legality/Tables4.cs
PKHeX/Legality/Tables5.cs
PKHeX/Legality/VivillonTables.cs

- Add a lengthy dream world table with special moves and levels (wonder if there is already a binary database). I guess location can be a good flag from PDW.
- Fixed a minor typo at vivillontables.
- Working on adding PGL Gift from Dream World (finished)

Add gen5 Dream World table

---

PKHeX/Legality/Structures/EncounterStatic.cs
PKHeX/Legality/Tables5.cs

- Add N's Pokemon
- Add Dream Radar Encounters
- Move the gift Norua to Static
- Warp tables up using `region`
- Static: regular = starters+fossils+gift+stationary+event+roaming+N's Pokemon (`Nsparkle`) / Dream World including PGL event gift (`location = 75`) / Dream Radar (`location = 30015`)
- Slots: regular = single+double+shaking+surf+surfspot+fish+fishspot / swarming / Hidden Grotto (`slottype = HiddenGrotto`)
- In-game Trade: regular, Yancy/Curtis
- Mystery gifts
- Shiny: N's Pokemon and Hidden Grotto captures can't be shiny
- OT/TID: N's Pokemon
- Ability: Hidden Grotto captures (done) and pkm from Dream World/Dream Radar should have HA (if it has), other HA pkm have been marked
- IVs: all IVs of N's Pokemon =30
- ball: pkm from DW can be in dream ball and from DR are all in a …

complete gen5 encounters database

---

PKHeX/Legality/Checks.cs
PKHeX/Legality/Core.cs
PKHeX/Legality/LegalityCheckStrings.cs
PKHeX/Legality/Tables3.cs
PKHeX/Legality/Tables4.cs
PKHeX/PKM/PK4.cs
PKHeX/PKM/PK5.cs
PKHeX/PKM/PK6.cs
PKHeX/PKM/PK7.cs
PKHeX/Resources/text/en/LegalityCheckStrings_en.txt

pkm.WasEgg is never true for gen 3 pokemon because there is no egg data to identify. Like gen 2 assume every pokemon above level 5 in pokeball that can be hatched from an egg that are eggs
For this pokemon check always for an egg encounter first, if does not match egg encounter then check other encounters
When verify moves for this pokemon it here is a non egg possible encounter first check moves from that encounter and if does not match check egg moves
Also for gen 2 unhatched eggs ignore gen 1 encounters

Gen3 WasEgg Pokemon in gen 4 or later, Gen 4 transfer encounter

---

PKHeX/Legality/Checks.cs
PKHeX/Legality/Core.cs
PKHeX/PKM/PK4.cs

Changed verifyEncounterG3Transfer, when both Egg Result and NonEgg Result happens Egg only overwrite if is the only valid encounter, if a normal result can be found and is possible to have a valid egg encounter then return egg encounter.
Also add checks on gen 3 WasEvent pokemon, but for now it will return Mistery Gift not found because there is no gen 3 events database, is better than give non-event errors. Special conditions for Mew and Deoxys.
Changed verifyEncounterG3Transfer and verifyEncounterG4Transfer to return both message error for InvalidTransfer and G3/G4 invalid encounter if both errors happen at the same time
And last excluded fateful encounter pokemon from getWasEgg23, it cant be WasEgg pokemon because FatefulEncounter from eggs is lost when hatch in gen 3 games

Fix issue #1001 Better approach for verifyEncounterG3Transfer function

---

PKHeX/Legality/Core.cs
PKHeX/Legality/Tables3.cs
PKHeX/Legality/Tables4.cs

Added static encounter for gen 3 and 4 game corner pokemon prizes
Fix Squirtle gen 3 starter encounter
Add met location to gen 3 ingame trades
Add minimun level for gen 3 RSE ingame trades, to do FRLG trades
Fix gen 3 level up tables, should return for every pokemon level up moves from one RSE game and one FRLG game, FRLG is different than RSE

Fix gen 3 level up moves and add some missing g3/4 encounters

---

PKHeX/Legality/Checks.cs
PKHeX/Legality/Core.cs
PKHeX/Legality/Structures/EncounterStatic.cs
PKHeX/Legality/Structures/EncounterTrade.cs
PKHeX/Legality/Tables4.cs
PKHeX/Legality/Tables5.cs

- begin to impl ball checking
- add white forest encounters for white 
- move greatmarshaltslots to table4
- fix several datapoints
- fix ability from dream world for pkm has no HA
- add version exlusive in-game trade filtering

General gen5 fixes

---

PKHeX/Legality/Checks.cs
PKHeX/Legality/Core.cs
PKHeX/Legality/Structures/EncounterArea.cs
PKHeX/Legality/Tables4.cs

Remember getValidWildEncounters was implemented to filter by ball for safari zone and bug catching contest in case there were more that one possible encounter, that means to check safariball and sportball checking the first slot is enought.
getValidWildEncounters will never return an array of slot with safari and non safari encounters at the same time, nor bug-catching encounters and non bug-catching encounters

Safari ball and sport ball checking

---

PKHeX.WinForms/MainWindow/Main.Designer.cs
PKHeX.WinForms/MainWindow/Main.cs
PKHeX.WinForms/MainWindow/MainCK3.cs
PKHeX.WinForms/MainWindow/MainXK3.cs
PKHeX/Game/GameVersion.cs
PKHeX/Legality/Checks.cs
PKHeX/Legality/Core.cs
PKHeX/Legality/Tables1.cs
PKHeX/Legality/Tables2.cs
PKHeX/PKHeX.Core.csproj
PKHeX/Saves/SAV3Colosseum.cs
PKHeX/Saves/SAV3GCMemoryCard.cs
PKHeX/Saves/SAV3RSBox.cs
PKHeX/Saves/SAV3XD.cs
PKHeX/Saves/SaveFile.cs
PKHeX/Saves/SaveUtil.cs
README.md

I added code extracted based on Dolphin to read pokémon gamecube savegames directly from memory card raw files without needing to extract the save to a gci file.
It allow to load gc files from gci like before but also for raw files, the format used by dolphin and also by many hombrew programs to backup real memory cards. It allow to export the save readed to the save memory card file or to extract the save to a gci file.
It does not allow to create a new memory card from a gci file nor resize or change the memory card. only allow to export the edited data to a memory card file if was imported from a memory card file, it is saved without altering any other savegames present in the memory card.
If there is more than one pokemon savegame in the same card it ask the user what save to edit. …

Load GC Memory Card files and some fixes

---

PKHeX/Game/GameVersion.cs
PKHeX/Legality/Analysis.cs
PKHeX/Legality/Checks.cs
PKHeX/Legality/Core.cs
PKHeX/Legality/Structures/EvolutionTree.cs
PKHeX/Legality/Tables1.cs
PKHeX/Legality/Tables2.cs
PKHeX/Saves/SAV3GCMemoryCard.cs

getValidStaticEncounters changed to return a list, the treatment of the list is similar than the mistery gift list for events encounters, it works like mistery gift encounters, the dragonite from DreamWorld in the issue #1011 now its flagged as legal
Also changed gen 1 and gen 2 encounters to take into account that the min species for an encounter can be a gen 2 preevolution, like tyroge -> hitmonlee, hitmonchan. 
When searching for static and wild encounters in gen 1 and 2 it will be used the maxSpecies of the game where the encounter is being searched, not the maxSpecies from the pkm format, the ordenation should return the min species in the evolutionary family tree, again tyrogue before himonlee or hitmonchan
Separate VC Events for GBCart Events. The event mew was being excluded in …

Static encounter refactor to return a list for pokemon with multiple statics but different moves

---

PKHeX/Legality/Analysis.cs
PKHeX/Legality/Checks.cs
PKHeX/Legality/Core.cs
PKHeX/Legality/Structures/EncounterStatic.cs
PKHeX/Legality/Tables3.cs

- there is a encounterstatic entry of Eevee egg in sm, needs to mark EncounterStaticMatch as null after checking. It happens when it's not the gift Eevee egg, i.e it has valid relearn moves
- remove some unnecessary code after refactoring
- skip valid level up move when checking levelup egg moves (wasegg pokemon)
- Add PokePark Encounter
- Add Egg Pokémon Present Eggs Encounter
- Fix gen3 eggs encounter recognition

Fix gen7 Eevee eggs checking and cleanup

---

PKHeX/Legality/Core.cs
PKHeX/Legality/Structures/EncounterArea.cs
PKHeX/Legality/Tables4.cs

- Change reference offset to absolute offset in order to read data independently and for troubleshooting
- Swarms species ID of dppt can be read from encounter raw file (2 x int32 starting from 0x66)
- [Swarms species ID of hgss is at 0xBE but lacking encounter type info]
- Timereplace slots of dppt only have morning and night slots, the 1st slot is just swarms
- Pokeradar slots should replace normal slots 4,5,10,11 (tested)
- While replacing slots, skip the encounters with same species ID (always because there is no such slots)

Fix and simplify gen4 encounter file reading 

---

PKHeX/Legality/Core.cs
PKHeX/Legality/Structures/Learnset.cs
PKHeX/Legality/Tables1.cs

I added some other  edge cases i found where the function getUsedMoveSlots was returning an incorrect value.
Most of the cases are
- Pokemon evolved before learning the 4th move at the base species, the 4th move is optional until the level when the evolve species learn it.
- Pokemon with exclusive yellow moves, those moves are optional
- Stone evolutions and Pikachu/Nidoran family. I reworked those. The only mandatory moves are the initial moves from the base species and in Pikachu/Nidoran family cases there is one mandatory level up move. All the other level up moves are optional.
I have checked Bulbapedia level up tables of generation 1 species i think there are no more edge cases, the function should return the correct number of mandatory used slots.

Generation 1 No move deleter edge cases

---

PKHeX/Legality/Structures/EncounterArea.cs

Species ID is read before level. Found the mapping method between raw data and actual number
but can't figure out any direct function between them

Fix yellow super rod encounters reading

---

PKHeX/MysteryGifts/PGF.cs

Identified an issue with force-ability and force-shiny WCs where the PID was off.
For example:
Original PID was A3134B185
Ability Forced to Ability 1
Forced to be Shiny
PID should be 03720085.  PKHex generated it as 03720084.
There MIGHT be an issue with force ability HA. I have theories on it, but would need to disassemble or generate them to see what actually happens.

Fixes gen 5 force-shiny generation.

---

PKHeX/Legality/Checks.cs
PKHeX/Legality/Core.cs

Fix three legallity error
- Base Species for generation 1 pokemon when cheking egg encounter data. GetBaseSpecies was returning always generation 1 species even in functions like getBaseEggMoves or getEggMoves. For a gen 1 Pikachu with an egg encounter the programa was searching for Pikachu egg moves instead of Pichu egg moves. I added a new function to return base egg species that will return generation 2 preevolutions when format is 1, only to be used when cheking egg data
- Fix ability check for generation 3 trades, the seadra reported in Issue #1011 
The validation abilities[pkm.AbilityNumber >> 1] != pkm.Ability should be ignored from generation 3 that do not match PID with ability in generation 4. Also the encounter trade validation for generation 3 pokemon should be done normal in …

Fix legallity issues

---

PKHeX/Legality/Core.cs

There is in the national park a butterfree encounter as a normal wild pokemon and another with the same levels in the bug contest, that means even in format 4 it could exits more than one type encounters in the list, it should be filtered

Fix Bug Contest Butterfree error reported in issue #1011

---

PKHeX/Legality/Checks.cs
PKHeX/Legality/Core.cs
PKHeX/Legality/LegalityCheckStrings.cs
PKHeX/Legality/Structures/EncounterStatic.cs
PKHeX/Legality/Tables.cs
PKHeX/Legality/Tables4.cs
PKHeX/Resources/text/en/LegalityCheckStrings_en.txt
PKHeX/Resources/text/ko/LegalityCheckStrings_ko.txt
PKHeX/Resources/text/zh/LegalityCheckStrings_zh.txt

I added validation for pokemon that evolve while leveling up with a specific move learned.
Those pokemon if they have 4 moves they must have at least one move learned after the evolution or the move that make them evolve. The valid moves are those that can be learned after evolving, including realearn moves, and the moves that trigger the evolution. At least one move must be from this valid moves.
For example a generation 5 eevee transfered to XY that have 4 non-fairy egg moves must forget one move and learn a fairy type move to evolve into Sylveon. If that Sylveon have those 4 moves is illegal.
Excluded are Sudowoodo and Mr.Mime from generation 1-3, pokemon with empty moves (they can forget the evolve move) and pokemon wich encounter is the evolved species. Also Sudowoodo and Mr.Mime are …

Move validation for evolutions by move, and fix static typed encounters

---

PKHeX/Legality/Core.cs
PKHeX/Legality/Tables4.cs

Added bug contest as tail grass encounters
Illex Forest as cave encounter
Mark encounter types in the final encounter array to avoid to have none encounter in any alt slot
Also i found discrapancies with heabutt and rock smash encounters, but i need to test catching pokemon from that encounters before make any changes.
It seems it not as easy as assign none to all headbutt encounters. Headbutt have the encounter type were the player is standing when he/she catch the pokemon. That means a headbutt encounter can have none, tail grass , cave or combination of tail and none depending of the area with maybe different values for normal trees and special tress.
Also i have found a rock smash encounter in Cianwood City with building encounter, maybe rock smash also change encounter value based in …

Fix Encounter Type checks

---

PKHeX/Legality/Checks.cs

Transfer legality is not checked if the pokemon is a valid static encounter
Also an Entei with invalid encounter is returning null as check encounter making the analysis to throw an exception, reported in the forum. 
Changed to do not return checkresult until the end to add invalid values if Gen4Result is null.

Fix error in transfer legality G4.

---

PKHeX/Legality/Checks.cs
PKHeX/Legality/Core.cs
PKHeX/Legality/Tables4.cs

Fix issue with egg pokemon reported in the forums, gen 4 transfer analysis was returning wild encounters for a pokemon that was an egg
Added encounter type to swarms and pokeradar safari slots
Split DP and Pt fossils, they have different encounter type
Change Drifloon and Spiritomb to encounter static without type, that stationary pokemon are not in a tail grass tile
Added Encounter Type to Burned Tower Suicune 
Added Maniac Tunnel to cave Location

Fix issue #1095 and gen 4 egg encounter issue from forums

---

PKHeX/Legality/Tables7.cs

This is long overdue since Pikachu-Original (along with the Z-Crystal) was released on April 15

Unban Pikashunium Z

---

PKHeX.WinForms/PKHeX.WinForms.csproj
PKHeX.WinForms/packages.config
Tests/PKHeX.Tests/PKHeX.Tests.csproj
Tests/PKHeX.Tests/Saves/Substructures/MemeCryptoTests.cs
Tests/PKHeX.Tests/packages.config

Closes #1123 
This should also fix the Team City test build.

Add missing package for MemeCrypto in .Net Framework

---

PKHeX.WinForms/MainWindow/Main.cs

Workaround for PKHaX being broken. Trimming each argument allows "hax", "-hax", and "--hax" to all work for activating illegal mode. Case insensitivity is because case sensitivity is annoying.
Original issue [here](https://projectpokemon.org/forums/forums/topic/40651-illegal-mode-issue/). Additional binding information:
```
=== Pre-bind state information ===
LOG: DisplayName = System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
(Fully-specified)
LOG: Appbase = file:///<path>/PKHeX.WinForms/bin/x86/Release/
LOG: Initial PrivatePath = NULL
Calling assembly : PKHeX.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: No application configuration file found.
LOG: Using host configuration file: …
```

Activate illegal mode with command-line arg

---

PKHeX.WinForms/Resources/text/shortcuts.txt
PKHeX.WinForms/Subforms/SAV_FolderList.cs

- Add close function when button is clicked for desired path
- Update Shortcuts
Personally, I found it annoying when the window was still open after choosing a path, as all I want to do afterwards is seamlessly drag/drop a SAV onto the form without having to close the Folder List every single time I open it up.

Folder List enhancements

---

PKHeX.Core/Legality/Checks.cs
PKHeX.Core/Legality/LegalityCheckStrings.cs
PKHeX.Core/Resources/text/en/LegalityCheckStrings_en.txt
PKHeX.Core/Resources/text/ko/LegalityCheckStrings_ko.txt
PKHeX.Core/Resources/text/zh/LegalityCheckStrings_zh.txt

A small check for ot gender in GC and GB pokemon.
Gamecube games and generation 1 games do not have female player character.
Also generation 2 is not checked because if the pokemon is in format 2 and have met location data stored that means it was caught in crystal where female player is allowed, checks are not included for generation VC2 pokemon, we do not know how the bank will transfer ot gender of crystal pokemon if VC2 games are released

Mark OT Female trainer from Gamecube and VC pokemon as invalid.

---

PKHeX.Core/Legality/Encounters/EncounterGenerator.cs

Prevents NullReferenceException if location is set in other Gen. Reference: https://projectpokemon.org/forums/forums/topic/40749-beautifly-and-dustox-re-roll-pidencryption-pkhex-becomes-unresponsive/

Fix Link Gift Check if not Gen 6

---

PKHeX.Core/Legality/Tables4.cs
PKHeX.Core/PKM/PKM.cs
PKHeX.Core/Util/RandUtil.cs
PKHeX.WinForms/Controls/PKM Editor/PKMEditor.cs

Set Shiny button will make any gen 3/4 pokemon illegal because the PID find wont match a PID/IV relation.
But Shiny can be obtained also changing the TID/SID of the pokemon instead of the PID and in most cases this wont make the pokemon illegal. Used SID instead of TID because the first data is ont visible in-game.
Changed shiny button to turn pokemon into shiny changin the SID instead of the PID if ctrl+click is used. The user can choose what data to change to make it shiny, normal click for the PID or ctrl+click for the SID.
Of course this change will make the pokemon foreign for its original trainer.

Set Shiny SID

---

PKHeX.Core/Legality/Core.cs
PKHeX.Core/Legality/Encounters/VerifyCurrentMoves.cs
PKHeX.Core/Legality/Structures/ValidEncounterMoves.cs
PKHeX.Core/Legality/Tables.cs

Two things
Fix issue #1200
Generation 2 VC without move reminder.
We can assume generation 2 wont have move reminder in the VC version because the only gen 2 game with move reminder is Pokemon Stadium 2, that means for generation 2 moves would work like in gen 1, only allowed the encounter moves and moves from one level after the minimun level to capture the pokemon
I have not done yet the part of move incompatibilities like generation 1. Is the part on gen 1 where we check a pokemon do not have two moves learned at the same level in redblue and yellos, also cheks that it do not have moves learned as an evolution at lower level that moves from a preevolutions. I talk about the functions ParseRedYellowIncompatibleMoves and ParseEvolutionsIncompatibleMoves. Also a third check should me …

Fix issue #1200 and added speculation for Gen2 VC without move reminder

---

PKHeX.Core/Saves/SAV4.cs
PKHeX.WinForms/Subforms/Save Editors/Gen4/SAV_Misc4.Designer.cs
PKHeX.WinForms/Subforms/Save Editors/Gen4/SAV_Misc4.cs

- Rename `CurrentPokeTchApp` to `CurrentPoketchApp`
- Properly hide Underground Flag Label/NUD for HG/SS save files
- Revise Battle Frontier labels
Previous implementation was confusing
In-game uses "Previous" and "Record", not "Current" and "Max" when checking past records
- Properly align several interface items

Misc4 updates

---

PKHeX.Core/PKHeX.Core.csproj
PKHeX.WinForms/PKHeX.WinForms.csproj
PKHeX.WinForms/packages.config
Tests/PKHeX.Tests/PKHeX.Tests.csproj
Tests/PKHeX.Tests/packages.config

I recently learned about targetting multiple frameworks in .Net Standard libraries. The main benefit here is that PKHeX.WinForms and PKHeX.Tests no longer need to carry around the .Net Core DLLs. While it's now an option, I encourage PKHeX.Core to avoid framework-specific compiler directives.
I don't know if PKHaX will work again after this change, although I don't see why not, besides the code changes. (Although to be fair, I didn't see why not when it wasn't working.)
The Windows Team City build is compatible with this change. The Mono build is fixed, but it paused because I expect normal builds will no longer work until this PR is completed.

Target netstanard1.3 and net46

---

PKHeX.WinForms/Subforms/Save Editors/Gen3/SAV_Misc3.Designer.cs
PKHeX.WinForms/Subforms/Save Editors/Gen4/SAV_Misc4.Designer.cs

Here's what's changed:
- "Previous" label in Gen 4 Misc Editor reverted to "Current"
Did not make sense if "Continue" checkbox wasn't checked
- Carry over most quality of life changes from my previous Misc4 PR to Misc3; includes the following
- "Is." -> "Island"
- "Lv50" -> "Lv. 50"
- "Pokemon" -> "Pokémon"
- "B.Frontier" -> "Battle Frontier"

Misc3 and Misc4 changes

---

PKHeX.Core/Legality/Tables3.cs

Added Froslass to FutureEvolutionsGen3, a gen 3 Froslass will now return true when executing function InhabitedGeneration for generation 3

Fix inhabited generation 3 for Frosslass

---

PKHeX.Core/Saves/SAV4.cs

Resolves the fifth bug detailed in #1297.

Fix D/P Mail Item offset

---

PKHeX.Core/Legality/Tables4.cs

Finally got around to actually testing this. The PKM in question is a legitimately caught Gastly in Platinum. My previous PR, as suggested by @javierhimura, was NOT the actual fix. This PR remedies this by checking for the correct Encounter Type, rather than not having one checked for at all.
Before **and** after first PR, PKHeX checked for "None", which was the bug initially brought up in #1297.
With this PR, it properly checks for "Building/Enigma Stone" and flags "None".

Actually fix Old Chateau Encounter Type

---

PKHeX.Core/Legality/Tables7.cs

Now all Mega Stones are legal in Gen 7.
https://twitter.com/PokemonLegality/status/895525097745678337

Unban Diancite

---

PKHeX.Core/Legality/Encounters/EncounterGenerator.cs

Fix generation 1/2 encounters for pokemon with different initial moves in yellow/crystal than r/b/g/s
The encounter generator was returning always RBY and GSC and that make the ParseMovesGenGB to check only for rb and gs learnset for initial moves, the version returned should be the game from the encounter to make ParseMovesGenGB use the correct learnset table for the initial moves
Closes #1417

Fix generation 1/2 encounters from issue #1417

---

PKHeX.Core/Legality/Analysis.cs
PKHeX.Core/Legality/Core.cs

Change VC1 pokemon tradeback initial status to TradebackStatus.Any. With the release of VC2 there is no way to know if a VC1 pokemon was traded to gen7 after or before VC2 release (user can change clock date). That means VC1 pokemon should be TradebackStatus.Any by default, to allow VC2 encounters and moves.
The only exception are female shiny pokemon impossible with VC2 formula, those pokemon are only legal with TradebackStatus.Gen1NonTradeback, but if we let the status to Any it will change to WasTradeback if there is a gen2 only data, and PKHex will flag the pokemon as illegal.
Also do not allow gen1 evolutions for VC2 pokemon without gen1 evolutions or preevolutions, like gen2 starters.

VC1 pokemon with VC2 tradeback

---

PKHeX.Core/Legality/Analysis.cs
PKHeX.Core/Legality/Checks.cs
PKHeX.Core/Legality/Core.cs
PKHeX.Core/Legality/Encounters/EncounterGenerator.cs
PKHeX.Core/Legality/Encounters/VerifyCurrentMoves.cs
PKHeX.Core/Legality/LegalityCheckStrings.cs
PKHeX.Core/Legality/Structures/ValidEncounterMoves.cs
PKHeX.Core/PKM/PK1.cs
PKHeX.Core/PKM/PK2.cs
PKHeX.Core/PKM/PKM.cs
PKHeX.Core/Resources/text/en/LegalityCheckStrings_en.txt
PKHeX.Core/Resources/text/ko/LegalityCheckStrings_ko.txt
PKHeX.Core/Resources/text/zh/LegalityCheckStrings_zh.txt
PKHeX.WinForms/MainWindow/Main.cs

Most of this checks are included because generation 1 and 2 games do not allow trade between games with different language, except games in western languages. With GB carts any trade between games with different RAM values result in save corruptions and VC games do not allow cross-language trade (not even between western languages)
Korean:
There is no Korean release for gen 1 pokemon, included VC games
https://bulbanews.bulbagarden.net/wiki/Pok%C3%A9mon_Gold,_Silver_coming_to_Nintendo_3DS_Virtual_Console
"The Generation I Virtual Console games were not released in South Korea either. " 
No gen1 games means any Korean gen2 is Gen2_NotTradeback, that means no gen1 origin nor moves are legal
Crystal was never released in Korean, probably when crystal is finally released in VC there will not …

Korean and Chinese restrictions

---

PKHeX.WinForms/Subforms/Save Editors/Gen4/SAV_Misc4.cs

Before this change:
You can see I'm currently using Matchup Checker, yet PKHeX says I haven't unlocked it. Was the same with D/P :)

Fix off-by-one Poketch offsets

---

PKHeX.Core/Legality/Tables7.cs

Can never be obtained outside of Bug Catching Contest.

Ban Sport Ball

---

PKHeX.Core/Legality/Encounters/Data/Encounters7.cs

Also removes Necrozma form entries; it's just like B2W2 in that you need to catch the two separate and then fuse them.

Add Poipole location

---

PKHeX.Core/Legality/Encounters/Data/Encounters7.cs

- Add Legendaries (seemingly all Ultra Space Wilds)
- Add Tapus
- Add Ultra Beasts
- Add version exclusivity
- Add both Type: Null gifts (if Party/PC are full, Wicke goes to Aether Paradise for you to pick it up later)
- Remove duplicate Pinsir
Can't confirm Buzzwole and Kartana until we have access to Ultra Sun, but if I had to guess based off of trailers...
- Buzzwole: Ultra Jungle
- Kartana: Ultra Forest
After cheating in 100 Totem Stickers, did not obtain Totem-Sized Gumshoos, Lurantis, Vikavolt, or Ribombee; probably Ultra Sun exclusives. Wouldn't make sense for Mimikyu to be version exclusive since two Electric-types (Vikavolt/Togedemaru).

Add more static encounter locations

---

PKHeX.Core/Legality/Encounters/Data/Encounters7.cs

Added:
- Cosmog locations
- Grubbin location (after catching tutorial)
Removed:
- Pikipek (leftover from SM, no early-game static encounter at that low level)
- Nihilego (first visit to Aether Paradise, can't catch)
- Yungoos (forced first encounter after starter in US, no Poke Balls at that point)
- Rattata (forced first encounter after starter in UM, no Poke Balls at that point)
- Spearow (forced fight at Plank Bridge, no Poke Balls at that point)
- Exeggutor (leftover from SM, there are no static Exeggutor on Exeggutor Island; only Pinsir)
- All Pokemon found during Trials (Dewpider, Masquerain, Fomantis, Sudowoodo, etc.)
- All Totem Pokemon + SOS allies (Araquanid, Marowak, Salazzle, Togedemaru, Ribombee)
Only a few remain unknown (like the random Lv58 Rattata lol)

Update USUM static encounter list

---

PKHeX.Core/Resources/text/script/const_usum_en.txt
PKHeX.Core/Resources/text/script/flags_usum_en.txt

Adds:
- Partner Cap Pikachu
- Cosmog
- Magearna
- Zygarde
- Totem-Sized Gifts
Flags from SM relating to Cosmog and Magearna aren't used for them in USUM. The flags from USUM that are used for them, however, are re-used elsewhere, but un-setting them does in fact allow you to re-collect both of them (did quite a few tests in-game).
Found how to re-collect Type: Null at Aether Paradise, but it involves re-setting 2 separate event flags and I don't know a good way of implementing that. For your own reference, you need to set these 2 flags:
- 0654
- 1101
Also an interesting thing: immediately catching Zygarde sets the constant value to 3, but over time it automatically gets changed to 5; I just left `05:Captured` in since you're hardly ever gonna see it be 3 after capturing Zygarde.

Add more USUM event flags/constants

---

PKHeX.Core/Resources/text/script/flags_usum_en.txt

In order to re-collect Type: Null, both event flags must be unset.

Add more USUM event flags

---

PKHeX.Core/Resources/text/script/flags_usum_en.txt

Stakataka APPEARABLE means NOT CAPTURED,
I think the latter will get misunderstand as CAPTURED,
so I adopt former.

add USUM UB flags

---

PKHeX.Core/Resources/text/script/flags_usum_en.txt

- Move Cosmog below Type: Null (in accordance to National Dex order)
- Add Blacephalon
- Rename Stakataka + Lunala
After testing, unsetting flag 1627 respawned either Legendary. The exact same save file imported to both US and UM with that one flag unset had both respawn at Mahalo Trail.
Thanks @pokecal for finding Lunala and Stakataka to begin with :)

USUM event flag updates

---

PKHeX.Core/Resources/text/script/flags_usum_en.txt

As discussed on IRC. For reference...
Cosmog: after receiving, sets flags 0503 and 1471. Setting 0503 respawns Cosmog with the Solgaleo/Lunala cutscene, while setting 1471 also respawns Cosmog but *without* aforementioned cutscene. 0503 is not re-used, but 1471 is.
Magearna: after receiving, sets flags 0276, 1469, and 4447. Setting any of the 3 will respawn Magearna, but 0276 isn't re-used like the latter two (1469 unknown, 4447 Nihilist Battle Style).

Fix Cosmog/Magearna flags

---

PKHeX.Core/Resources/text/script/flags_usum_en.txt

Apparently I received Magearna in between my before/after saves for Nihilist. Thank you @SciresM for pointing out the Magearna event flag to me! Strange how 0276, 1469, and 4447 do the same thing, and that all Battle Styles but one are consecutive.

Fix Nihilist flag

---

PKHeX.Core/Legality/Encounters/Data/Encounters7.cs

Old Amber unobtainable in Gen 7 as of now (possibly forever).

Comment out Old Amber Aerodactyl

---

PKHeX.Core/Legality/Tables6.cs
PKHeX.Core/Legality/Tables7.cs

Unban safari ball Slakoth, Pichu and Igglybuff, beast ball Helioptile.

Breeding ball legality fixes

---

PKHeX.Core/Legality/Encounters/Data/Encounters6.cs

Noticed using recent pk3DS additions.

Add XY gift Lapras ability check

---

PKHeX.WinForms/Subforms/Save Editors/SAV_GameSelect.cs

Bug found while trying to load a LeafGreen save on mono:
```Exception Details:
System.NotImplementedException: The method or operation is not implemented.
at System.Linq.Enumerable+Iterator`1[TSource].System.Collections.IEnumerator.Reset () [0x00000] in <2392cff65f724abaaed9de072f62bc4a>:0 
at System.Windows.Forms.BindingSource.GetListFromEnumerable (System.Collections.IEnumerable enumerable) [0x00066] in <2f8b04a5fbc8420bbb3895e91a62c74f>:0 
at System.Windows.Forms.BindingSource.ResetList () [0x000a3] in <2f8b04a5fbc8420bbb3895e91a62c74f>:0 
at System.Windows.Forms.BindingSource..ctor (System.Object dataSource, System.String dataMember) [0x0002d] in <2f8b04a5fbc8420bbb3895e91a62c74f>:0 
at (wrapper remoting-invoke-with-check) System.Windows.Forms.BindingSource:.ctor (object,string)
at …
```

Fix a crash bug when loading Gen 3 saves on mono

---

PKHeX.WinForms/MainWindow/Main.cs
PKHeX.WinForms/Subforms/Save Editors/SAV_GameSelect.cs

IEnumerable doesn't support LINQ methods, only the generic variant does. So this commit changes SAV_GameSelect's parameter to a generic IEnumerable of the only type being passed into it. I didn't realize it until afterward, but this is 100% the way it should have been because the databinding members expect ComboItems.

Fix build error

---

PKHeX.Core/Legality/Checks.cs
PKHeX.Core/MysteryGifts/WC6.cs
PKHeX.Core/MysteryGifts/WC7.cs

IV lock doesn't work for IV3 case (Issue happens in Shiny Poipole WC7, all IVs besides HP are 31)
General WC  IVs check for [PGL Pikachu](https://github.com/projectpokemon/EventsGallery/blob/master/Released/Gen%206/Wondercards/JPN/1510%20ORAS%20-%20PGL%20Pikachu%20(JPN).wc6full) 
Source: ORAS: sub_45FB84 UMv1.2: sub_454408  https://pastebin.com/bbpS6svw

Fix WC6/7 IV generation

---

PKHeX.WinForms/Controls/PKM Editor/PKMEditor.cs

Remove SelectedIndexChanged EventHandler to skip ValidateMove and allow moves to populate, then set back SelectedIndexChanged EventHandler

Fix Suggested Move Set

---

PKHeX.Core/Resources/text/de/lang_de.txt
PKHeX.Core/Resources/text/en/lang_en.txt
PKHeX.Core/Resources/text/es/lang_es.txt
PKHeX.Core/Resources/text/fr/lang_fr.txt
PKHeX.Core/Resources/text/it/lang_it.txt
PKHeX.Core/Resources/text/ja/lang_ja.txt
PKHeX.Core/Resources/text/ko/lang_ko.txt
PKHeX.Core/Resources/text/other/lang_pt.txt
PKHeX.Core/Resources/text/zh/lang_zh.txt
PKHeX.WinForms/MainWindow/Main.cs

Added translation strings for Apply Showdown Markings in CHS, French, and Korean. International schools ftw.
Additionally, Portuguese was not accessible as it is Index 9 ("zh2", which I assume is CHT, is at 8), so I've just hardcoded this bit since I don't know if anything else relies on lang_val.

Translate Showdown Markings & Fix PT Selection

---

PKHeX.Core/PKM/ShowdownSet.cs

The current implementation has issues with nicknames when there is no item on the `ShowdownSet`. There are 4 ways in which Showdown has the first line implemented
```
Species
Species (Gender)
Nickname (Species)
Nickname (Species) (Gender)
```
The current implementation will only have `speciesstr` equivalent to the species string in case of the first 2 cases mentioned above. In case of the third and fourth cases, it tries to match the nickname to the species name, and fails to do so and hence `Species = -1` is left as it is, resulting in an invalid set.
Since the current fallback mechanism modifies the species value anyway and will only be hit when the first line does not contain an item, the implementation in this PR is a much more cleaner and a foolproof one, since `ParseFirstLine` …

Fix Showdown Import issues

---

PKHeX.Core/PKM/ShowdownSet.cs

Showdown Set imports for Nidoran are of the format: `Nidoran-G (G)` or `Nidoran-G`  where G is the gender represented by M/F. The current logic for handling edge cases with species that have a `-` in their name does not account for the Nidorans.
The string replace on line `287` is needed because we cannot simply trim the gender symbols since that would not properly specify the gender in species. So the cases when a showdown set is imported without specified gender (i.e. `Nidoran-G` format and not `Nidoran-G (G)` format) then the code would not be able to differentiate between the genders of either nidoran and so will just default to the male nidoran (032) even though the intended Showdown imports specify female nidoran since the male one comes before in the `var edge` list. This is why I …

Fix Showdown Imports for Nidoran

---

PKHeX.WinForms/Controls/SAV Editor/SlotChangeManager.cs

Local functions are cool and all, but for something this simple, it just hurts readability and makes things needlessly complex.

Simplify logic in PlayCry

---

PKHeX.WinForms/Controls/PKM Editor/PKMEditor.cs

Is there a reason for having GSC newTrack as USUM? This causes `origintrack = newTrack;` not to happen and thus controls don't switch from G2->G7 correctly.

Correct Control Switching for G2->G7

---

PKHeX.Core/Legality/RNG/Locks/LockFinder.cs

If SIDf >> 16 != SID then temp won't be assigned.

Fix Colo Starter PID Method Check

---

PKHeX.WinForms/Controls/PKM Editor/StatEditor.cs

Reset IV backcolor if pkm cannot be hypertained

---

PKHeX.Core/Saves/SAV1.cs

This commit implements `IsDaycareOccupied` for generation 1 saves. The
byte which tracks if the daycare is occupied should normally only be
0x01 or 0x00, so I decided that all other values mean that the daycare
is probably corrupted and thus not occupied. `SetDaycareOccupied` is not
implemented, since I am not sure what other flags the game normally sets
in this scenario and the daycare is read-only anyway.
The GUI displays the Pokemon's index to the right for some reason, but I
don't have saves to test this for other generations, so it might be
unrelated to this change.

Implement IsDaycareOccupied for SAV1

---

PKHeX.Core/Legality/Tables7.cs

Because the Berry are now Released on Gen7, allow Items now on Legality Check: Enigma, Micle, Custap, Jaboca
Edit: Just Commented out, u prolly want to remove them completly from the table.

Update for Latest Berry Event

---

PKHeX.WinForms/Subforms/Save Editors/Gen7/SAV_ZygardeCell.Designer.cs
PKHeX.WinForms/Subforms/Save Editors/Gen7/SAV_ZygardeCell.cs

Now you can sort the Available stickers to the top.
Also a change to have the "Ref" sort integers instead of strings.
Now it doesn't go 1\n11\n etc

Column sorting changes for ZygardeCell editor

---

PKHeX.Core/Saves/SAV7.cs

The current wormhole's shiny flag & pokemon can be changed with these functions.
The flags & offsets were found by @PP-theSLAYER https://projectpokemon.org/home/forums/topic/39433-gen-7-save-research-thread/?page=3&tab=comments#comment-239090
I haven't comprehensively tested each slot and wormhole to confirm the correctness (yet). This is assuming theSLAYER's table was correct.
I didn't make a subform because I've never made GUIs in C# and because I want to see if this code needs to be changed first (like the slot base, 0, or max variable, 4). Maybe more comments too...

Add USUM Wormhole functions

---

PKHeX.Core/Saves/Substructures/Gen7/WormholeInfoReader.cs

changed slot numbering from 0-4 to 1-15
fixed drapion's pokedex number in wormhole slot table

add legendary pokemon to wormhole slots

---

PKHeX.Core/PKM/Shared/_K12.cs

PK1 and PK2 get the equivalent of 1 EV added after taking the square root
PP Ups on 40-PP moves don't just get the override of 3=>61, but also 2=>54 and 1=>47

Fix a couple off-by-one logic errors in early gens

---

PKHeX.Core/Legality/Tables/Tables7b.cs

https://twitter.com/PokemonGoApp/status/1122954828483846144
Also, apparently Shiny Alolan Raichu has been available since November (oops?)

Update GO shiny banlist

---

PKHeX.Core/Resources/text/de/MessageStrings_de.txt
PKHeX.Core/Resources/text/en/MessageStrings_en.txt
PKHeX.Core/Resources/text/es/MessageStrings_es.txt
PKHeX.Core/Resources/text/fr/MessageStrings_fr.txt
PKHeX.Core/Resources/text/it/MessageStrings_it.txt
PKHeX.Core/Resources/text/ja/MessageStrings_ja.txt
PKHeX.Core/Resources/text/ko/MessageStrings_ko.txt
PKHeX.Core/Resources/text/zh/MessageStrings_zh.txt
PKHeX.Core/Util/MessageStrings.cs
PKHeX.WinForms/MainWindow/Main.cs

Makes it clearer for conversion failure with Pokemon files - prevent confusion with save files.

Enhance Invalid Convert Error

---

PKHeX.WinForms/Subforms/Save Editors/Gen4/PoffinCase4Editor.cs

Poffin names are hyphen separated.

Make Poffin names match in-game text

---

PKHeX.Core/Legality/Encounters/Data/Encounters5.cs

Poliwag, Chansey, Togetic, Magneton, Dragonair and Shelgon, as per Funfest Week 3 Hidden Grotto encounters.

Added Funfest week 3 encounters

---

PKHeX.Core/Legality/Encounters/Data/Encounters5.cs

According to the link below, the official page states that Poliwag's announcement was a mistake, and they clarified it would not be appearing.
This message was echoed across various pages (Sapporo, Fukuoka, Tohoku), not just the Yokohama one.
https://voice.pokemon.co.jp/stv/yokohama/2013/08/post-2286.html
Additionally, based on tests from me and jojo, Funfest missions forces the grotto encounters to be max level (of the individual grottoes).
https://projectpokemon.org/home/forums/topic/39810-unlock-all-funfiesta-missions/?do=findComment&comment=245303

Removed Special Funfest Poliwag & updated min Lvl.

---

PKHeX.Core/Saves/SAV6AO.cs

Would've otherwise resulted in:

Fix ORAS held items/personal reference

---

PKHeX.Core/Legality/Tables/Tables7b.cs
PKHeX.Core/Legality/Verifiers/IndividualValueVerifier.cs

All Shiny Alola Forms are releasing; modify Verifier to allow Shiny Alola Form while still flagging the respective Kanto Form (if not released).
Changes go live at 20:00 UTC today (in just over 2 hours), getting it out of the way now.

Update GO Shiny banlist for GO 3rd Anniversary

---

PKHeX.Core/Legality/Encounters/Data/Encounters7b.cs

Now Dratini/Meltan aren't flagged!

Fix off-by-one

---

PKHeX.Core/Saves/SAV4HGSS.cs
PKHeX.Core/Saves/SAV4Sinnoh.cs
PKHeX.Core/Saves/Substructures/Gen7/BoxLayout7.cs
PKHeX.WinForms/Subforms/Save Editors/Gen6/SAV_BoxLayout.cs

Box Name length is 8 characters in Gen. 2/3/4/5 (JPN included), and 14 in Gen. 6/7. No reason to let the user enter more characters than the game allows, just like Nickname and OT fields. This also fixes an issue that would occur in Gen. 2 when setting 9 characters-long box names, where it would wipe the name of the box after it.
I don't know how many characters Sword/Shield allow for boxes, so this may need to be adjusted for G8.
Fixes a bug in G4 where editing a box's name wiped the name of the box after it. Setting the maximum length of the string to 8 fixes this (hardcoded value bad, but this works at a glance, and can be improved later.)
Fixes a bug in G7 where editing a box's name applied it to the wrong box.

Box Layout fixes

---

PKHeX.Core/Legality/Tables/Tables7b.cs

Edit: When I told you about Shiny Meowth, it was only from Team GO Rocket (non-transferable)... but a day later it got added to wild lmao

Unban GO Shiny Tentacool

---

PKHeX.Core/Editing/CommonEdits.cs

When using showdown import, the `CanGigantamax` boolean was being set for the ShowdownSet object but it was not being set when applying details to a pkm object

set gigantamax flag from showdown set

---

PKHeX.Core/Legality/Encounters/Data/Encounters8.cs

Gyarados Spawns in Area 1:
North/East/South/West Lake Miloch, 
Area 2:
the Lake of Outrage (in a Wild Area)

Add Multiple Gyarados Spawns

---

PKHeX.Core/Editing/ShowdownSet.cs

Full amped form has no form string, so does not need fixing. Exporting low key form also adds a hyphen, so that does not need fixing either!

fix toxtricity parsing

---

PKHeX.Core/Legality/Encounters/Generator/EncounterMovesetGenerator.cs

EncounterMovesetGenerator was using the de-evolution order in the passed evocriteria list

grab correct evo stage 1 from evocriteria list

---

PKHeX.Core/Legality/Verifiers/TransferVerifier.cs

Alolan Forms can't be obtained yet, same with Hoenn Zigzagoon/Linoone and Unova Stunfisk.

Update Gen 8 transfer banlist

---

PKHeX.Core/Editing/ShowdownSet.cs

sometimes competitive sets have multiple moves in one slot as optional coverage moves. Handle these cases by splitting and trimming over '/'.  Example: https://pastebin.com/raw/jvPziRdC (The dusk mane set)

handle smogon sets with multiple moves

---

PKHeX.WinForms/Subforms/Save Editors/Gen5/SAV_Misc5.Designer.cs

since battle subway records has a maximum of 9999 for your record. non-super formats don't really need a maximum, but i included it anyways.
i also included some tab indexing so people can navigate the window with a keyboard, and a minor fix to the "record" labels so you can read them.

set gen 5 battle subway record max to 9999 + tab indexing

---

PKHeX.Core/Saves/Substructures/Gen8/TrainerCard8.cs

In other interesting news, a Block file with all available clothing was posted on PP!: https://projectpokemon.org/home/files/file/4041-fashion-block/
Maybe it could be implemented into PKHeX? I'm sure a lot of peps would love this! :)

Add Gender to Gen 8 Trainer Card

---

PKHeX.Core/Legality/Tables/Locations.cs

Skyarrow Bridge is more popular to hatch at legitimately.

Change Gen 5 hatch location

---

PKHeX.Core/Saves/Access/SaveBlockAccessor8SWSH.cs

Because the Switch doesn't have a feature to internally store your B-day like the DS and 3DS does, you set it in-game by the "Fortune Girl" right in front of Wedgehurst's PokeCenter in month and day. 
Can't be changed afterwards.
https://www.serebii.net/swordshield/birthdays.shtml

Add SwSh Birthday blocks

---

PKHeX.WinForms/Subforms/PKM Editors/BatchEditor.cs

Running a batch editor job in the same window pops the alert message in incrementing numbers until the window is closed.

Batch Editor Alert Fix

---

PKHeX.Core/Saves/Access/SaveBlockAccessor8SWSH.cs

Here's the structure for the NPC card data. Very straightforward :)
Owned: 0 = No 1 = Yes
Date: YYMD values
Hop
Owned 0x00
Date 0x2-5
Hop (Rare)
Owned 0x08
Date 0xA-D
Marnie
Owned 0x10
Date 0x12-15
Marnie (Rare)
Owned 0x18
Date 0x1A-1D
Milo
Owned 0x20
Date 0x22-25
Milo (Rare)
Owned 0x28
Date 0x2A-2D
Nessa
Owned 0x30
Date 0x32-35
Nessa (Rare)
Owned 0x38
Date 0x3A-3D
Kabu
Owned 0x40
Date 0x42-45
Kabu (Rare)
Owned 0x48
Date 0x4A-4D
Bea
Owned 0x50
Date 0x52-55
Bea (Rare)
Owned 0x58
Date 0x5A-5D
Allister
Owned 0x60
Date 0x62-65
Allister (Rare)
Owned 0x68
Date 0x6A-6D
Opal
Owned 0x70
Date 0x72-75
Opal (Rare)
Owned 0x78
Date 0x7A-7D
Gordie
Owned 0x80
Date 0x82-85
Gordie (Rare)
Owned 0x88
Date 0x8A-8D
Melony
Owned 0x90
Date 0x92-95
Melony (Rare)
Owned 0x98
Date 0x9A-9D
Piers
Owned 0xA0
Date …

Add blocks for NPC and Friend League Cards

---

PKHeX.Core/Saves/Substructures/Gen3/SecretBase3.cs
PKHeX.WinForms/Subforms/Save Editors/Gen6/SAV_Trainer.cs

This is so that the OT_Class will be consistent with the other classes with only getters and not setters.

Change OT_Class to body extension form

---

PKHeX.Core/Saves/SAV3.cs

In #2785 I incorrectly stated that RSE had the same offsets for decorations, but this was a mistake from the pret disassemblies. They are further in the block in Emerald, so this commit fixes that. It also throws an exception if the sav is FRLG since there are no decorations in those games.

Fix Emerald decorations

---

PKHeX.WinForms/MainWindow/Main.cs
PKHeX.WinForms/Util/WinFormsUtil.cs

If you open a file called "E.sav" and save it as "E2.sav", PKHeX will still believe the current save file is "E.sav" and will have that as the title of the program and the default filename when exporting which may lead to you overwriting the original save file accidentally. This PR will correctly update the title bar and the sav object.

Fix sav path after exporting to new name

---

PKHeX.Core/Legality/Areas/EncounterArea8.cs

made an oopsie, Watchtower Ruins also apparently includes 2 extra dens that can spawn encounters that are not 8NC. Den 17 is locked to 8NC encounters only, but location-wise there is no difference between Den 15,16,17

add back watchtower as a legal location

---

PKHeX.Core/PKM/Util/FormConverter.cs

Very trivial, but we noticed these typos while working on https://github.com/smogon/pokemon-showdown/pull/6669 and correcting them seemed like the least we could do to show our thanks. Sorry for the PR-overhead for such a minuscule change, thank you to all the PKHeX contributors for the great insight into how the game actually works! :)

Fix minor typos in FormConverter comments

---

PKHeX.Core/Saves/Substructures/Gen8/RaidSpawnList8.cs

the normal raids have 100 before and the raids count of armor area should be 90?

Update legal raid counts

---

PKHeX.Core/Legality/Encounters/Data/Encounters8.cs

The static spawn point right outside Brawlers' cave, all of the pokemon are able to chase the player into the cave and be caught
https://cdn.discordapp.com/attachments/401014193211441161/724112694088695918/a0f06577821f60edf119308675de7894.png
https://cdn.discordapp.com/attachments/401014193211441161/724117077698281502/JPEG_20200621_002242.jpg
Unsure if there were more that spawn in this point that have the same behaviour, but these were the ones I found (w/ Ano0onymouse
for Shield ones)

Additional Cross Boundary Edge Cases

---

PKHeX.Core/Legality/Encounters/EncounterStatic/EncounterStatic8ND.cs

Fixes false flagging on distribution raids caught in The Isle of Armor.

Update IsMatchLocation to allow Isle of Armor Dens

---

PKHeX.Core/Legality/Verifiers/MiscVerifier.cs

SWSH changed Rockruff->Lycanroc to only depend on time of day, not Version as well. Cosmoem still needs both, though.

Update VerifyVersionEvolution for Gen 8 Lycanroc

---

PKHeX.Core/Legality/Encounters/Data/Encounters7b.cs

This'll probably end up being deprecated in the future when we have GO->HOME transfer checks, in addition to IV checking, but update this for now since I don't think we'll get that functionality until the second coming of Christ.

Update GO minimum Level requirements

---

PKHeX.Core/Editing/ShowdownSet.cs

Gigantamax: Yes is now in a new line instead of -Gmax. Have maintained legacy support since showdown is supporting legacy as well. Set the export to the newer format.

update showdownset parsing for new gmax impl

---

PKHeX.Core/Editing/CommonEdits.cs
PKHeX.Core/PKM/Shared/IHyperTrain.cs

Now that Hidden Power is removed from the game in gen 8, IVs have no battle relevant side effects and only affect the pokemon's stats. This means that any IVs specified in the showdown format are deliberate for stat purposes and should not be hyper trained over.
The main use case for this is allowing sysbots to gen trick room pokemon with a specific amount of speed creep without bleeding into another speed tier.

Changes to suggested hyper training logic 

---

PKHeX.WinForms/Util/FontUtil.cs

It appears that some users are experiencing an issue where the PrivateFontCollection cannot find the font that should have been written to the temporary path. Move the AddFontFile call into the try-catch block so that PKHex doesn't crash in this event.
Link to Issue: https://projectpokemon.org/home/forums/topic/57234-pkhex-200414-error/

Handle Exception When Adding Font File

---

PKHeX.Core/PKM/PKM.cs
PKHeX.Core/PKM/Shared/GBPKM.cs
PKHeX.WinForms/Controls/PKM Editor/StatEditor.Designer.cs
PKHeX.WinForms/Controls/PKM Editor/StatEditor.cs
Tests/PKHeX.Core.Tests/PKM/HiddenPowerTests.cs

The power calculations for Hidden Power used the incorrect bit. Fixed for both Gen II and Gen III-V. Added Power calculations to UI for Gens 1-5 where they are applicable

Fix Hidden Power Power calculations (and add to UI)

---

PKHeX.Core/PKM/PK1.cs

I plan to use this property to improve Auto-Legality Mod's Generation I Tradebacks legality. Currently ItemConverter is internal and therefore cannot be interfaced with by plugins. Alternatively the scope of ItemConverter could be increased (or code could be copied, but I'd like to avoid this if possible)

Add property to get a PK1's converted Gen 2 item

---

PKHeX.Core/Legality/Encounters/Data/Encounters8.cs

Before I added PKHeX formatted dumping to pkNX, I added the gifts by hand and missed this!
Only allow Ability 1, and moved to a lower line for tidiness.

Restrict Isle of Armor Raichu-1 Ability

---

PKHeX.Core/Legality/Encounters/Data/Encounters2.cs

Met + Current level data for non-Egg PCNY Pokémon and Egg legality for PCNY Pokémon fixed.

Clean up Gen 2 PCNY Events

---

PKHeX.Core/Saves/Access/SaveBlockAccessor8SWSH.cs

Thanks RoC! https://github.com/kwsch/PKHeX/commit/36a9ef05db903aad71ca6db4ce06b6f0c2ed3a33#r43573614
I tested this Block just now and can confirm it changed what Pokemon Peonia hints at next, and NOT the first entry saved.

Added one more Max Lair Block

---

PKHeX.Core/Legality/Areas/EncounterArea8.cs

Not related to the location glitch; whistle to lead Zigzagoon.
Co-Authored-By: tehvik <40148574+tehvik@users.noreply.github.com>

Add Route 3 -> Motostoke City crossover

---

PKHeX.Core/Legality/Encounters/Data/Encounters8.cs

~~The only unique Pokémon from the Zeraora Challenge is the level 17 G-Max Snorlax.  All others are duplicated or uncatchable.~~
Some of the static encounters are fog-only, which only shows up in base Wild Area and IoA after beating the Champion.  Thus they can only be encountered at level 60 and cannot be distinguished from each other.  CT does not seem to have any fog restrictions.

Add missing static encounters

---

PKHeX.Core/Legality/Areas/EncounterArea8.cs
PKHeX.Core/Legality/Encounters/Data/Encounters8.cs
PKHeX.Core/Legality/Encounters/EncounterStatic/EncounterStatic8.cs

This only matches the weather table with the Pokemon and does not fully
account for whether a location can spawn a particular weather.
Additional minor changes:
- Adds ScriptedNoMarks to Regis and Glimwood Tangle static encounters
- Corrects a few version-specific Pokemon such as Ludicolo/Shiftry
- Removes erroneous encounters such as Milotic in East/West Lake Axewell
- Removes an unused Motostoke Stadium encounter

Document weather for static encounters

---

PKHeX.Core/Legality/Encounters/EncounterSlot/EncounterSlot.cs
PKHeX.Core/Legality/Encounters/EncounterSlot/EncounterSlot3PokeSpot.cs
PKHeX.Core/Legality/Encounters/EncounterSlot/EncounterSlot7.cs
PKHeX.Core/Legality/Encounters/EncounterStatic/EncounterStatic.cs
PKHeX.Core/Legality/Encounters/EncounterStatic/EncounterStaticShadow.cs
PKHeX.Core/Legality/Encounters/EncounterTrade/EncounterTrade.cs
PKHeX.Core/Legality/Encounters/EncounterTrade/EncounterTrade3.cs
PKHeX.Core/Legality/Encounters/EncounterTrade/EncounterTrade5.cs
PKHeX.Core/Legality/Encounters/Generator/EncounterCriteria.cs
PKHeX.Core/Legality/Formatting/BaseLegalityFormatter.cs
PKHeX.Core/Legality/Formatting/ILegalityFormatter.cs
PKHeX.Core/Legality/Formatting/LegalityFormatting.cs
PKHeX.Core/MysteryGifts/PGF.cs
PKHeX.Core/MysteryGifts/WB7.cs
PKHeX.Core/MysteryGifts/WC6.cs
PKHeX.Core/MysteryGifts/WC7.cs
PKHeX.Core/MysteryGifts/WC8.cs
PKHeX.Core/PKM/Shared/IRegionOrigin.cs
PKHeX.Core/PKM/Shared/ISpeciesForm.cs
PKHeX.Core/PersonalInfo/PersonalInfo.cs
PKHeX.Core/PersonalInfo/PersonalTable.cs
PKHeX.Core/Saves/Substructures/Gen7/GP1.cs
PKHeX.WinForms/Subforms/Save Editors/Gen6/SAV_HallOfFame.cs

Some miscellaneous xmldoc + minor tweaks elsewhere as I noticed them, but this change is `EncounterCriteria` changing the GetAbility (index) call sites.
Contains a tweak for WC7 to change the `Version` if it's the SMDEMO greninja card. Would be better if the Restrict values were used instead, but oh well.

Rework EncounterCriteria to be ability indexed rather than direct ability

---

PKHeX.Core/Legality/Encounters/Data/Encounters8.cs

Keeps them from showing up in encounter database.

Comment out locationless gen 8 static encounters

---

PKHeX.Core/Saves/SAV3Colosseum.cs
PKHeX.Core/Saves/SAV3XD.cs

Colosseum has a x99 limit for non-Key Items with the exception of Berries.
Also make XD's Discs 1 as they're technically Key Items.

Correct Colosseum/XD Item Quantities

---

PKHeX.Core/Legality/Formatting/LegalityCheckStrings.cs
PKHeX.Core/Legality/Restrictions/Vivillon3DS.cs
PKHeX.Core/Legality/Verifiers/FormVerifier.cs

This uses [more current crowdsourced information](https://docs.google.com/spreadsheets/d/e/2PACX-1vTVVOEZbXLVQvjIdzGACpZ_IrOWgVDBr_Wa-xULK3191BP9lf1tep-z-PsmcAfaH_aE56j3GHDX_9UO/pubhtml) to update the country and subregion tables for Vivillon forms. It's possible to change the country/subregion within a 3DS console region, so only forms that cannot be obtained for a console region are flagged as illegal. If a form is not native to the country/subregion, it is marked as Fishy instead.

Properly check Vivillon form legality

---

PKHeX.Core/PKHeX.Core.csproj

Azure Pipelines emits a warning during `dotnet pack` which causes the build to fail.
```
##[warning].NET 5 has some compatibility issues with older Nuget versions(<=5.7), so if you are using an older Nuget version(and not dotnet cli) to restore, then the dotnet cli commands (e.g. dotnet build) which rely on such restored packages might fail. To mitigate such error, you can either: (1) - Use dotnet cli to restore, (2) - Use Nuget version 5.8 to restore, (3) - Use global.json using an older sdk version(<=3) to build
##[error]Error: The process 'C:\Program Files\dotnet\dotnet.exe' failed with exit code 1
##[error]An error occurred while trying to pack the files.
```
Probably will work fine when NET 6 comes out and the pipeline agents are updated.

Only use the TreatWarningsAsErrors for debug build

---

PKHeX.Core/Legality/Restrictions/Memories/MemoryContext.cs
PKHeX.Core/Legality/Restrictions/Memories/MemoryContext6.cs
PKHeX.Core/Legality/Restrictions/Memories/MemoryContext6Data.cs
PKHeX.Core/Legality/Restrictions/Memories/MemoryContext8.cs
PKHeX.Core/Legality/Restrictions/Memories/MemoryContext8Data.cs
PKHeX.Core/Legality/Restrictions/Memories/MemoryPermissions.cs
PKHeX.Core/Legality/Verifiers/MemoryVerifier.cs

Includes the following new memory checks for gen 8 unless otherwise specified:
- 4: met in link-trade, allows all possible genlocs except dangerous place
- 7: successful fishing, allows fishable species in gen 6 and 8
- 9: paying attention to another mon, allows only available species for gen 8
- 29: encountering legendary Pokémon, only seen on Zacian, Zamazenta, Calyrex so far
- 32: riding a bike, only in genlocs where biking is possible
- 75: taken to Nursery and placed with a mon, allows only available species for gen 8
Unstubs lotto check for memory 51 and applies it to gen 6.
With this, only memories 12, 13, 18, and 25 have no checks at all for gen 8.

More memory legality checks

---

PKHeX.Core/Saves/SAV8BS.cs
PKHeX.WinForms/Subforms/Save Editors/Gen8/SAV_Trainer8b.cs

I saw it existed but was not populated/disabled, so I found the offset and added it in.
It works in my tests though I'm not sure what the max is (assuming 9999 from previous gens?) and I hope the saves are the same size and there's no offset issues. (I say other hard-coded offsets so I'm assuming this to be true as well.)
So this just unhides the existing NUD in trainer info and binds the data to the SAV.

Add/Enable BDSP Battle Tower Points (BP).

---

PKHeX.WinForms/Controls/SAV Editor/SAVEditor.cs

Replaces the generic winforms icon with PKHeX's icon.
The only known instance that I know of, changes the "Block Data" for BDSP saves.

Add PKHeX icon to generic/simple/whatever editor

---

PKHeX.Core/Saves/SAV4Pt.cs

The seed was being read/written to the wrong location of the save. I've tested this on my pokemon platinum savefile, diamond/pearl locations might be wrong as well, but I haven't checked those.

Fix swarm seed location for pokemon platinum

---

PKHeX.Core/Legality/Verifiers/MiscVerifier.cs
PKHeX.Core/PKM/PA8.cs
PKHeX.Core/PKM/PB7.cs
PKHeX.WinForms/Controls/PKM Editor/SizeCP.cs

Order of operations and specific mult/add constants, yay.
Reverse engineered, and PB7/PA8 are slightly different in their implementations:
* PA8 combines the Height & Weight ratios prior to multiplying `pi.Weight`
* PB7 multiplies the height ratio after the `Weight Ratio * pi.Weight`
* PB7 uses 0x3F4CCCCC (0.79999995f) for height ratio mult
* PB7 uses 0x3F4CCCCD (0.8f) for weight ratio mult
* Both use 0x3ECCCCCE (0.40000004f) in place of 0.4f
Removes the lowest-3-bit epsilon comparison legality check, as we can now check for strict equality.
Prevents updating the HeightAbsolute & WeightAbsolute when loading data into the `SizeCP` control, resolving the behavior issue in #3416.

Emulate Height & Weight float calculations matching the game

---

PKHeX.Core/Saves/SAV3.cs
PKHeX.Core/Saves/SAV3Colosseum.cs
PKHeX.Core/Saves/SAV3RSBox.cs
PKHeX.Core/Saves/SAV3XD.cs
PKHeX.Core/Saves/SAV8LA.cs
PKHeX.Core/Saves/SAV8SWSH.cs
PKHeX.Core/Saves/SaveFile.cs
PKHeX.Core/Saves/SaveFileState.cs
PKHeX.Core/Saves/Util/SaveUtil.cs
PKHeX.WinForms/Controls/SAV Editor/SAVEditor.cs
PKHeX.WinForms/MainWindow/Main.cs

Stop allocating an entire shadow copy of the save file whenever we create a new savefile object from file.
Prior commits added the clear SaveFileMetadata class to cleanly track the file path. Backups are copied from the original path.

Minimize BAK file allocations

---

PKHeX.Core/Legality/Encounters/EncounterSlot/EncounterSlot8a.cs
PKHeX.Core/Legality/Encounters/EncounterStatic/EncounterStatic8a.cs
PKHeX.Core/Legality/RNG/Algorithms/Xoroshiro128Plus.cs
PKHeX.Core/Legality/RNG/Overworld8aRNG.cs
PKHeX.Core/Saves/Access/ISaveBlock8LA.cs
PKHeX.Core/Saves/Access/SaveBlockAccessor8LA.cs
PKHeX.Core/Saves/SAV8LA.cs
PKHeX.Core/Saves/Substructures/Gen8/LA/Spawners/AreaSpawnerSet8a.cs
PKHeX.Core/Saves/Substructures/Gen8/LA/Spawners/Spawner8a.cs
PKHeX.Core/Saves/Substructures/Gen8/LA/Spawners/SpawnerEntry8a.cs
PKHeX.Core/Saves/Substructures/Gen8/LA/Spawners/SpawnerMeta8a.cs
PKHeX.Core/Saves/Substructures/Gen8/LA/Spawners/SpawnerUtil8a.cs
Tests/PKHeX.Core.Tests/Legality/Wild8aRNGTests.cs

Adds structures to read/write saved spawner data such as seeds, counts.
Adds generator and validator to emulate the FixInitSpec builder used by the game logic
Similar to SW/SH raids, validating these in-process is not feasible due to the number crunching required.
This does not handle the encounter slot call or the follow-up level range call. Just the inner FixInitSpec ctor & fill.

Add logic for PLA wild RNG correlation

---

PKHeX.Core/Resources/text/script/gen8/work_bdsp_en.txt
PKHeX.Core/Saves/Access/SaveBlockAccessor8LA.cs

So I started a second playthrough, and was also documenting the stuff I was interested in.
-Includes the block that tells the game you chose Adaman over Irida. Nothing important seemed to change on my side during the course of the initial story other than the KDefeatedOriginDialga or KDefeatedOriginPalkia, so you may wanna revise those if you do change this I guess.
-Blocks that allow you to re-receive the unchosen starters; KStarterChoice affects the 2 you'll get.
-Blocks for the Rotom form appliances from Ginter for those who find it repetitive.
-Object block that appear to store the rematch best times for the Nobles, Origin Dialga, Origin Palkia, and Arceus.
Also included 2 BDSP event constants for the total amount of Master Class wins and the streak needed to achieve a prize in the …

Add L:A blocks and BDSP event constants

---

PKHeX.Core/Legality/Encounters/EncounterStatic/EncounterStatic.cs
PKHeX.Core/Legality/Encounters/Generator/EncounterCriteria.cs
PKHeX.Core/Legality/Structures/Shiny.cs
PKHeX.Core/MysteryGifts/ShinyType6.cs
PKHeX.Core/MysteryGifts/ShinyType8.cs
PKHeX.Core/MysteryGifts/WA8.cs
PKHeX.Core/MysteryGifts/WB7.cs
PKHeX.Core/MysteryGifts/WB8.cs
PKHeX.Core/MysteryGifts/WC3.cs
PKHeX.Core/MysteryGifts/WC6.cs
PKHeX.Core/MysteryGifts/WC7.cs
PKHeX.Core/MysteryGifts/WC8.cs

Have `Shiny.Random` be `0`, so we can skip init on this field for EncounterStatic. Plus makes it a little less brittle for future expansion if shiny qualities change.

Disassociate Shiny enum from WC6 PIDType

---

PKHeX.Core/Editing/Saves/Slots/Info/SlotOrigin.cs
PKHeX.Core/Legality/Encounters/EncounterSlot/EncounterSlot3.cs
PKHeX.Core/Legality/Encounters/Generator/EncounterFinder.cs
PKHeX.Core/Legality/Encounters/Verifiers/EncounterVerifier.cs
PKHeX.Core/Legality/Encounters/Verifiers/VerifyCurrentMoves.cs
PKHeX.Core/Legality/Encounters/Verifiers/VerifyRelearnMoves.cs
PKHeX.Core/Legality/Enums/CheckIdentifier.cs
PKHeX.Core/Legality/Enums/Severity.cs
PKHeX.Core/Legality/Formatting/LegalityCheckStrings.cs
PKHeX.Core/Legality/Formatting/LegalityFormatting.cs
PKHeX.Core/Legality/LegalityAnalysis.cs
PKHeX.Core/Legality/Moves/Breeding/BreedInfo.cs
PKHeX.Core/Legality/Structures/CheckMoveResult.cs
PKHeX.Core/Legality/Structures/CheckResult.cs
PKHeX.Core/Legality/Structures/ICheckResult.cs
PKHeX.Core/Legality/Structures/LegalInfo.cs
PKHeX.Core/Legality/Structures/MoveSource.cs
PKHeX.Core/Legality/Verifiers/LegendsArceusVerifier.cs
PKHeX.Core/Legality/Verifiers/TransferVerifier.cs
PKHeX.Core/PKM/PKM.cs
Tests/PKHeX.Core.Tests/Legality/LegalityTests.cs

* Reuses move parse result objects for each encounter parsed in a LegalityCheck attempt, instead of creating a new object.
* Ensures the objects are never-null, and makes cleanup easier.
Slightly adjusts some other parts of the moveset validation to reduce allocations.

Performance: Slightly reduce allocations in moveset validation

---

PKHeX.Core/Legality/Moves/Breeding/MoveBreed2.cs
PKHeX.Core/Legality/Moves/Breeding/MoveBreed3.cs
PKHeX.Core/Legality/Moves/Breeding/MoveBreed4.cs
PKHeX.Core/Legality/Moves/Breeding/MoveBreed5.cs
PKHeX.Core/Legality/Moves/Breeding/MoveBreed6.cs
Tests/PKHeX.Core.Tests/Legality/BreedTests.cs

https://github.com/kwsch/PKHeX/commit/ddc6f414dfda8ec9e060f052138201258193cda0 caused it to be `<=` instead of `<`, but maybe the underlying issue was fixed a different way since all tests still pass with this reversion.

Revisions for bdsp gible

---

PKHeX.Core/PKHeX.Core.csproj
PKHeX.WinForms/Program.cs

_IsOldPkhexCorePresent_ was missing two possible exceptions (_TypeLoadException_ and _TypeInitializationException_).
Also the version check at the end was kinda redundant. PKHeX.Core didn't have a version set in its csproj, so ```AssemblyName.GetAssemblyName("PKHeX.Core.dll").Version``` always returned 1.0.0, which made the version comparison always beeing true.

Improved detection of old PKHeX.Core.dll

---

PKHeX.Core/Util/MessageStrings.cs
PKHeX.WinForms/Controls/SAV Editor/SAVEditor.cs

If the user has a directory copied to their clipboard, a prompt is displayed asking if they'd like to use that for box operations (dump/load) as an alternative to using the built-in FolderBrowserDialog.

Prompt user for clipboard directory use if present for box dump/save

---

PKHeX.Core/Saves/Substructures/Gen6/Situation6.cs

Divide by 18 was missing when getting the Z coord. This would modify the coordinate to an unwanted number when writing map data.

Fixed error getting Z coordinate in Gen6

---

PKHeX.Core/MysteryGifts/WC9.cs

TID and SID for wc9 mystery gifts is not pulled directly from the hardcoded value in the wondercards like it was in SwSh.
For example, the PokéCenter Flabébé wondercards have an hardcoded otid of 0x0012A1FE. This would've translate to Sid7 0001 and Tid7 221118.
This isn't the case for the legitimately code-redeemed Flabébé, which have Sid7 0000 and Tid7 221118 (different SID). 
I did some experiments by fabricating BCAT data with different wondercard IDs and different hardcoded OTIDs. The resulting Pokémons never obtained the hardcoded tid/sid.
The formulas in this PR will match the SID and TID obtained by redeeming a Pokémon through the Mystery Gift directly on the SV games.
After writing the code for this PR, I did few tests: loaded custom bcat datas in my switch games and those same …

Generate proper TID and SID from WC9

---

PKHeX.Core/Editing/CommonEdits.cs
PKHeX.Core/Saves/Substructures/Gen9/RaidSpawnList9.cs

This field must be set to a valid spawn point, so without ability to edit this via UI it wasn't possible to (re)spawn new raid crystals without resorting to block import option.

Added spawn points to raid editor

---

PKHeX.Core/Editing/ISpriteBuilder.cs
PKHeX.Core/Legality/Breeding.cs
PKHeX.Core/Legality/Encounters/Generator/Specific/EncounterEggGenerator.cs
PKHeX.Core/Legality/Restrictions/HeldItemLumpImage.cs
PKHeX.Core/Legality/Tables/FormInfo.cs
PKHeX.Drawing.PokeSprite/Builder/SpriteBuilder.cs
PKHeX.Drawing.PokeSprite/Builder/SpriteBuilder5668.cs
PKHeX.Drawing.PokeSprite/Builder/SpriteBuilder5668a.cs
PKHeX.Drawing.PokeSprite/Builder/SpriteBuilder5668c.cs
PKHeX.Drawing.PokeSprite/Util/SpriteName.cs
PKHeX.Drawing.PokeSprite/Util/SpriteUtil.cs
PKHeX.WinForms/Controls/Slots/CryPlayer.cs
PKHeX.WinForms/Controls/Slots/SummaryPreviewer.cs
PKHeX.WinForms/Subforms/KChart.cs
PKHeX.WinForms/Subforms/Save Editors/Gen5/SAV_Misc5.cs
PKHeX.WinForms/Subforms/Save Editors/Gen6/SAV_HallOfFame.cs

Changes the API for sprite building to use `EntityContext context` instead of `int Generation`.

Show star square for everything in Gen9

---

PKHeX.Core/Legality/Encounters/Generator/EncounterCriteria.cs
PKHeX.Core/Legality/RNG/Methods/Encounter9RNG.cs

In `Encounter9RNG`, the intention was to apply the override tera-type if the caller requested it, but the code was instead trying to assign the original type to the override type, meaning the criteria's tera-type was ignored by mistake
This PR corrects that and `EncounterCriteria` ignoring the `ShowdownSet` tera-type

Fix tera-type typo in Encounter9RNG

---

PKHeX.Core/Saves/Storage/SAV4Ranch.cs
PKHeX.Core/Saves/Substructures/Gen4/Ranch/RanchLevel.cs
PKHeX.Core/Saves/Substructures/Gen4/Ranch/RanchToyType.cs

These changes expand the RanchToyType enum with new entries for the Toys introduced in the Platinum Update, as well as the seemingly unused Poke Ball!
For compatibility, a check has also been added to prevent the Platinum Update toys being applied to the base game, as trying to load these new toys will cause the game to throw a corrupted save error.

Add Toys from the My Pokémon Ranch Platinum Update

---

PKHeX.Core/PKM/Shared/GBPKML.cs

Fixes a simple bug in Gen 2, where setting the "OT" field in PKHeX would cause the OT to appear as "?" in game:
I've tested this with my English copy of Crystal, but don't have any other languages or Gen 1 games to try it out on.
Being as this change mostly just removes duplicate functionality that got outdated in favour of another existing working implementation, it should hopefully be fine!

Update "SetStringKeepTerminatorStyle" to resolve "?" OT bug.

---

PKHeX.Core/MysteryGifts/WC9.cs

As seen in the recent Garganacl card (https://github.com/projectpokemon/EventsGallery/commit/482fe23d7c61545072528e8cbf46dcba4fb27d85), WC9 use Dev ID instead of Dex ID :)

Use Internal ID for Species in WC9

---

PKHeX.Core/Legality/Encounters/Data/Live/EncounterServerDate.cs
PKHeX.Core/MysteryGifts/WC9.cs

Adjusted the Flabébé entry and added the Gyarados entry in the EncounterServerDate class.
I didn't add the Garganacl entry yet, since its redemption code is supposed to be available later today (2023-02-16) at 10pm UTC.
Fixed the MetDate during a PK9 generation from a wondercard template:
1) I removed the `IsDateRestricted` bool check since all events are restricted anyways.
1) The `EncounterServerDate.WC9GiftsChk` was incorrectly called with `CardID` instead of card `Checksum`.
1) Added the `EncounterServerDate.WC9Gifts.TryGetValue` method call, which was missing.

Fix MetDate for WC9 templates

---

PKHeX.Core/Legality/Encounters/Data/Gen3/EncountersWC3.cs

Firstly: Wishmaker Jirachi has a static SID of 00000, so ID32 should probably be used instead of TID16. Otherwise Mystery Gift Database gives it an SID of 65535, and legality checker ends up accepting any SID for it even though 00000 is the only legal one.
Secondly: Duking trades (and Elekid) from XD have unspecified SIDs, which is normal because as far as I can tell, the game gives them the same SID as the player's. So any SID should be valid, but because unspecified SID = 65535, Mystery Gift Database only gives them 65535 SID. It's not a big deal, you can manually edit them for yourself, but I figured it would be nice if it would use the SID from the save file instead of defaulting to 65535, since that's what the game already does anyway. …

WC3 fixes/improvements (?)

---

PKHeX.Core/Saves/Access/SaveBlockAccessor9SV.cs

- Rename FSYS_Vivillon for uniformity
- Labels bool for GOVivillon form is enabled
- Labels unix time stamp for GOVivillon postcard expiration

Label SV GO Vivillon Save Blocks

---

PKHeX.WinForms/Controls/SAV Editor/SAVEditor.cs

I am making a plugin to automatize a Living Dex sorting and after sorting the boxes in the plugin and changing the box names, I noticed the method UpdateBoxViewers only reload the box content, not the names, so I added a call to ResetBoxNames.

ResetBoxNames in UpdateBoxViewers

---

PKHeX.Core/Saves/Access/SaveBlockAccessor9SV.cs

Data for a total amount of 8 outbreaks is always present within the game states, but the amount of those outbreaks that are effectively enabled (meaning visible in the map and that can produce spawns in the game world) is determined by block 0x6C375C8A.
For example, if block 0x6C375C8A contains the value "7", only the first 7 outbreaks will be effectively active. If the block contains "8", then all the outbreaks will be effectively active.
I tried to stay consistent with your block nomenclatures, but feel free to edit the label if you wish to.
Do note that since this is an SByte block, editing its value will require a fix to correctly handle the cast from object to data byte value. PR https://github.com/kwsch/PKHeX/pull/3843 can eventually be used for this.

Label Active Outbreaks Number Save Block

---

PKHeX.Core/Saves/Encryption/SwishCrypto/SCTypeCode.cs

Currently, when PKHeX tries to edit the value of an SCBlock of SByte type, it tries to cast the value from `object` to `byte`, which causes the exception `Unable to cast object of type 'System.SByte' to type 'System.Byte'`. 
This can be avoided by forcing a cast from `object` to `sbyte`, and only then to `byte`.

Fix SetValue for SByte blocks

---

PKHeX.Core/Saves/Access/SaveBlockAccessor9SV.cs
PKHeX.Core/Saves/SAV9SV.cs
PKHeX.Core/Saves/Substructures/Gen9/Epoch1900Value.cs

Add Epoch1900Value based on Epoch1970Value's API and the method @Lusamine described in #3800 to access the Enrollment Date From Scarlet and Violet Save

Add Enrollment Date To SaveBlockAccessor9SV and SAV9SV

---

PKHeX.Core/Items/ItemStorage6AO.cs
PKHeX.Core/Legality/Core.cs
PKHeX.Core/Legality/Restrictions/ItemRestrictions.cs
PKHeX.Core/Legality/Restrictions/Memories/MemoryContext6.cs
PKHeX.Core/Legality/Restrictions/Memories/MemoryContext8.cs
PKHeX.Core/Saves/SAV6AO.cs
PKHeX.Core/Saves/SAV6AODemo.cs
PKHeX.Core/Saves/SAV6XY.cs

- Add HeldItems_XY
- Fix that HeldItem_AO pointed to what should have been HeldItems_XY
- Fix HeldItem_AO being inconsistent with the rest of the HeldItems
- Correct HeldItems_AO only having XY  held items and not ones added in ORAS

Fix ORAS Held Items Using XY Held Items By Mistake

---

PKHeX.Core/Items/ItemStorage4HGSS.cs
PKHeX.Core/Items/ItemStorage4Pt.cs

As part of #3860, ItemStorage4Pt was created to reference Pouch_Items_DP instead of Pouch_Items_Pt, which causes the Griseous Orb in a Pt inventory to be declared nominally invalid. This PR is a trivial fix for this issue.

Fix Griseous Orb being incorrectly removed from Pt inventory

---

PKHeX.Core/Legality/Encounters/Data/Live/EncounterServerDate.cs
PKHeX.Core/MysteryGifts/WC8.cs

Handle Rev 2 cards in https://github.com/projectpokemon/EventsGallery/commit/5471ccc714b5753e68e8d9220dfd4d6edf59d95d
This uses the card checksum to distinguish revisions like we already do for the WC9 files.
This reverts some code from https://github.com/kwsch/PKHeX/commit/cd22cc64ce88d0259fe7bd71476692abcde3e4a3 since the PID is now handled by the Rev 2 cards.

Handle Rev 2 Home WC8 cards

---

PKHeX.Core/Legality/Encounters/Data/Live/EncounterServerDate.cs

The gift code was given on stream on June 10 at around 4:00 A.M UTC.
The wondercard was removed from the servers on June 11 at around 3:00 PM UTC.

Add そらみつ's Bronzong Server Date

---

PKHeX.Core/Saves/Storage/SAV4Ranch.cs

Spotted the cause! Wound up just being a case of a missing offset for an address calculation!
The data was getting zeroed out due to a bit of a domino effect - Because this argument was wonky, the data end marker was being put in the wrong place, then any data after that marker gets 0'd!

Correct SAV4Ranch's SetChecksums() passing the wrong pkEnd offset argument to UpdateMetadata()

---

PKHeX.Core/Game/GameStrings/GameStrings.cs
PKHeX.Core/Legality/Areas/EncounterArea8a.cs
PKHeX.Core/Legality/Encounters/EncounterSlot/EncounterSlot8a.cs
PKHeX.Core/Legality/Encounters/EncounterSlot/EncounterSlot9.cs
PKHeX.Core/Legality/Encounters/EncounterStatic/EncounterStatic8b.cs
PKHeX.Core/Legality/Encounters/EncounterTrade/EncounterTrade8b.cs
PKHeX.Core/Saves/SAV9SV.cs

1. Fixes a bug where the Pokemon tooltip for PLA incorrectly looks at the SwSh location table, resulting in nonsense locations showing
Screenshot before fix
Screenshot after fix
2. Fixes comments that refer to incorrect generations/versions/games for the particular file

Pokemon location tooltip fix for PLA + miscellaneous comment fixes

---

PKHeX.Core/Saves/SAV2.cs
PKHeX.Core/Saves/Substructures/Gen12/SAV2Offsets.cs

'Ello 'ello! Me again!
This PR addresses the issues @pikavees reported in #3890! - Looks like it was just a classic typo problem! I was able to recreate their scenario and confirmed that with these changes, it no longer occurs!
I've also added their suggestion to rejig the Checksum verification logic a bit to compare against both values, with it reporting which one(s) pass/fail!
Ta'!

Crystal (International) Checksum 2 Fix

---

PKHeX.Core/Saves/Substructures/PokeDex/Zukan9.cs

as explained in my discord message
the dex entry is gotten with
```
new PokeDexEntry9SV(Dex.GetScBlock().Data.AsSpan(SpeciesConverter.GetInternal9(x) * PokeDexEntry9SV.SIZE))
```
but the byte data passed into the PokeDexEntry9SV is not capped at PokeDexEntry9SV.SIZE so it just passes a lot of data into the PokeDexEntry9SV for example 48396 when getting Sprigatito instad of the PokeDexEntry9SV.SIZE 24 (0x18) the dex entry (PokeDexEntry9SV) does not seem to care about the extra data but when you call clear all the extra data that does not belong to the current dex entry also gets cleared

Fixed span for PokeDexEntry9SV being too large

---

PKHeX.Core/Ribbons/IRibbonSetCommon3.cs
PKHeX.Core/Ribbons/IRibbonSetCommon4.cs
PKHeX.Core/Ribbons/IRibbonSetCommon6.cs
PKHeX.Core/Ribbons/IRibbonSetCommon7.cs
PKHeX.Core/Ribbons/IRibbonSetCommon8.cs
PKHeX.Core/Ribbons/IRibbonSetCommon9.cs
PKHeX.Core/Ribbons/IRibbonSetEvent3.cs
PKHeX.Core/Ribbons/IRibbonSetEvent4.cs
PKHeX.Core/Ribbons/IRibbonSetMark8.cs
PKHeX.Core/Ribbons/IRibbonSetMark9.cs
PKHeX.Core/Ribbons/IRibbonSetMemory6.cs

Makes RibbonExtension public to be accessible from plugin projects
Notes:
Currently required for the Home Live Plugins to keep legacy support for old dumped PH1 and PH2 files.

RibbonExtensions public accessors

---

PKHeX.Core/Saves/Util/SaveUtil.cs

Three more G9 DLC Save Sizes, with a [report from](https://github.com/kwsch/PKHeX/pull/3995#issuecomment-1722535352) @laserjagd and based on my own save file before (`0x432EC4`) and after (`0x432EC9`) connecting to GO.

Other Additional G9 DLC Save Sizes

---

PKHeX.WinForms/MainWindow/Main.cs

This change allows plugins to get notified about a save being loaded by startup arguments.
Related issue: https://projectpokemon.org/home/forums/topic/62222-blacksharks-pkhex-plugin-support-thread/?do=findComment&comment=285534
User was dropping the save directly onto the exe.

Load plugins before loading initial files

---

PKHeX.Core/Saves/SAV4HGSS.cs
PKHeX.WinForms/Subforms/Save Editors/Gen4/SAV_Misc4.Designer.cs
PKHeX.WinForms/Subforms/Save Editors/Gen4/SAV_Misc4.cs

This PR adds support for editing the Pokeathlon Points in a HGSS save, which are used to purchase various evolution items.

HGSS: Add support for editing Pokeathlon Points

---

PKHeX.Core/Saves/Storage/SAV4Ranch.cs
PKHeX.Core/Saves/Substructures/Gen4/Ranch/RanchLevel.cs
PKHeX.Core/Saves/Substructures/Gen4/Ranch/RanchToyType.cs

This PR corrects an API/logic mismatch with the RanchLevel.cs methods, whereby the argument was labelled "levelIndex", but the logic assumed it was receiving the actual level value.
To try and simplify the implementation and reduce confusion in the future, I've changed the CurrentRanchLevelIndex and PlannedRanchLevelIndex getters/setters to just CurrentRanchLevel & PlannedRanchLevel to abstract the underlying structure, and updated the method signatures to clarify the argument they're expecting.

My Pokemon Ranch: Level fixes and general usability improvements

---

PKHeX.Core/Saves/Substructures/Gen7/FieldMoveModelSave7.cs
PKHeX.Core/Saves/Substructures/Gen7/Situation7.cs
PKHeX.WinForms/Subforms/Save Editors/Gen7/SAV_Trainer7.cs

Occasionally, changing the player's coordinates was causing the player to ride an invisible Pokémon on load. I determined that this was because FieldMoveModelSave has a uint16 value at offset 0 that appears to be correlated to the player's current Ride Pokémon, not just a copy of the map value. These are the values I observed:
- 1: on foot
- 5: Tauros
- 6: Sharpedo
- 12: Stoutland
- 13: Mudsdale
- 14: Machamp
- 15: Lapras
This doesn't appear to be the only value that determines the player's Ride Pokémon though, since changing it manually either keeps the player on their previous Ride Pokémon or has them mount an immovable, invisible Ride Pokémon. Because of this, I didn't add an accessor or form element for it.
The player's X/Z/Y coordinates appears to be stored as consecutive float32 …

Fix Gen 7 map position

---

PKHeX.Core/Saves/Access/SaveBlockAccessor8SWSH.cs

- Rename capture flags to more appropriate name since it is just if they are in the overworld or not.
- Document progress values for each Sword of Justice.

Document Sword and Shield Swords Of Justice Flags and Values

---

PKHeX.Core/Editing/Showdown/ShowdownSet.cs
PKHeX.Core/PKM/Interfaces/IGanbaru.cs
PKHeX.WinForms/Controls/PKM Editor/MoveChoice.cs
PKHeX.WinForms/Controls/PKM Editor/MoveDisplay.Designer.cs
PKHeX.WinForms/Controls/PKM Editor/MoveDisplay.cs
PKHeX.WinForms/Controls/PKM Editor/PKMEditor.cs
PKHeX.WinForms/Controls/SAV Editor/SlotChangeManager.cs
PKHeX.WinForms/Controls/Slots/PokePreview.Designer.cs
PKHeX.WinForms/Controls/Slots/PokePreview.cs
PKHeX.WinForms/Controls/Slots/SlotHoverHandler.cs
PKHeX.WinForms/Controls/Slots/SummaryPreviewer.cs
PKHeX.WinForms/MainWindow/Main.cs
PKHeX.WinForms/Properties/PKHeXSettings.cs
PKHeX.WinForms/Subforms/SAV_Database.cs
PKHeX.WinForms/Subforms/SAV_MysteryGiftDB.cs
PKHeX.WinForms/Subforms/Save Editors/SAV_GroupViewer.cs

When the user hovers over a slot in their Box / Party, PKHeX displays a tooltip indicating details about the Pokémon. This text tooltip shows the `Showdown` text (with some localization based on program setting), and includes details about the encounter the legality check matched it to.
Example:
The tooltip functionality is slightly clunky and isn't feasible to customize; instead, we can create a popup form and stylize it as we wish. This pull request adds a replacement to the existing behavior.
New behavior can...
* be reverted by the user via program settings, to instead use the old tooltip.
* turn off extra details (encounter details, and paste too).
* adjust the positioning the form appears at, relative to the user's cursor.
Additional behaviors implemented:
* Moves are shown with …

Enhanced Slot Hover Preview

---

PKHeX.Core/Saves/SAV1.cs
PKHeX.Core/Saves/Substructures/Gen12/G1OverworldSpawner.cs

This PR adds a secondary heuristic based on PikaFriendship value, that has a fixed value of 90 when save data is initialized in YW, and is always 0 in RB.
This covers the small gap between the time the user can perform the first save game, and when the Starter was received.
As alternative check, it was discovered that an unused Hide-Show flag in YW is kept always set, while in RB this is always unused flag data.
`Version = Data[Offsets.ObjectSpawnFlags + 0x1D] != 0x00 ? GameVersion.Y : GameVersion.RB;`
Also, changes to 'G1OverworldSpawner' so that it checks by Version instead of Starter value that may not be set yet.
Having this distinguished as early as first save point, it allows plugins to behave correctly with known data.

Secondary heuristic to distinguish SAV1 save files versions

---

PKHeX.Core/Resources/text/script/gen5/flags_b2w2_en.txt
PKHeX.Core/Resources/text/script/gen5/flags_b2w2_es.txt
PKHeX.Core/Resources/text/script/gen5/flags_b2w2_ja.txt
PKHeX.Core/Resources/text/script/gen5/flags_b2w2_ko.txt
PKHeX.Core/Resources/text/script/gen5/flags_b2w2_zh.txt
PKHeX.Core/Resources/text/script/gen5/flags_b2w2_zh2.txt

Tested myself.
Courtesy from https://projectpokemon.org/home/forums/topic/64099-no-event-flags-for-volcarona-black-2-white-2/

Add B2W2 Volcarona Event Flags

---

PKHeX.Core/Resources/text/script/gen5/const_b2w2_en.txt
PKHeX.Core/Resources/text/script/gen5/const_b2w2_es.txt
PKHeX.Core/Resources/text/script/gen5/const_b2w2_ko.txt
PKHeX.Core/Resources/text/script/gen5/const_b2w2_zh.txt
PKHeX.Core/Resources/text/script/gen5/const_b2w2_zh2.txt
PKHeX.Core/Resources/text/script/gen5/const_bw_en.txt
PKHeX.Core/Resources/text/script/gen5/const_bw_es.txt
PKHeX.Core/Resources/text/script/gen5/const_bw_ko.txt
PKHeX.Core/Resources/text/script/gen5/const_bw_zh.txt
PKHeX.Core/Resources/text/script/gen5/const_bw_zh2.txt
PKHeX.Core/Resources/text/script/gen5/flags_b2w2_en.txt
PKHeX.Core/Resources/text/script/gen5/flags_b2w2_es.txt
PKHeX.Core/Resources/text/script/gen5/flags_b2w2_ja.txt
PKHeX.Core/Resources/text/script/gen5/flags_b2w2_ko.txt
PKHeX.Core/Resources/text/script/gen5/flags_b2w2_zh.txt
PKHeX.Core/Resources/text/script/gen5/flags_b2w2_zh2.txt

Adds one for the P2 Lab event and fixed the Volcarona event flags space formatting that caused them to not display up on the interface.

Update Gen5 Event Flags

---

PKHeX.Core/Legality/Restrictions/Memories/MemoryContext6.cs
PKHeX.Core/Legality/Restrictions/Memories/MemoryContext8.cs

From the saves I have it appears that memory intensity goes from 0 to 7 rather than 0 to 6.

Fix Max Memory Intensity

---

PKHeX.Core/Resources/text/locale3DS/subregions/sr_001.txt
PKHeX.Core/Resources/text/locale3DS/subregions/sr_039.txt
PKHeX.Core/Resources/text/locale3DS/subregions/sr_043.txt
PKHeX.Core/Resources/text/locale3DS/subregions/sr_047.txt
PKHeX.Core/Resources/text/locale3DS/subregions/sr_049.txt
PKHeX.Core/Resources/text/locale3DS/subregions/sr_074.txt
PKHeX.Core/Resources/text/locale3DS/subregions/sr_077.txt
PKHeX.Core/Resources/text/locale3DS/subregions/sr_097.txt
PKHeX.Core/Resources/text/locale3DS/subregions/sr_100.txt
PKHeX.Core/Resources/text/locale3DS/subregions/sr_128.txt
PKHeX.Core/Resources/text/locale3DS/subregions/sr_144.txt

Fixes some typos by grabbing the names from region manifest v5122, the last version for 3DS.
TW has all of its subregions censored as a dash in CHS, so they're instead translated from CHT.

Fix 3DS country/region names

---

PKHeX.Core/Saves/Substructures/Gen8/SWSH/RaidSpawnList8.cs
PKHeX.Core/Saves/Substructures/Gen9/RaidSpawnList9.cs
PKHeX.WinForms/Controls/SAV Editor/SAVEditor.cs
PKHeX.WinForms/Subforms/Save Editors/Gen8/SAV_Raid8.cs
PKHeX.WinForms/Subforms/Save Editors/Gen9/SAV_Raid9.cs
PKHeX.WinForms/Subforms/Save Editors/Gen9/SAV_RaidSevenStar9.cs

Use an enum to know which raids to use rather than passing the specific raids so that the save changes copy back operation only happens when a user saves modifications and thus won't flag the save as modified if nothing was changed.

Make Raid Editors Edit Copies Rather Than Origin Save's Data

---

PKHeX.Core/PKM/Strings/StringConverter12.cs
PKHeX.Core/PKM/Util/SpeciesName.cs
Tests/PKHeX.Core.Tests/PKM/StringTests.cs

- For consistency with ベ/ペ/リ which are treated as katakana here and in StringConverter12Transporter.cs, map 0xCD to katakana ヘ instead of hiragana へ.
- Allow input of hiragana べ/ぺ/へ/り, mapping them to katakana ベ/ペ/ヘ/リ. Previously, they would be treated as invalid and mapped to the string terminator.
- Previously, 0xE8 was mapped to U+002E `.` FULL STOP, while 0xF2 was mapped to the special character U+2024 `․` ONE DOT LEADER. Since 0xF2 is used in user input while 0xE8 is only used in `MR.MIME`, swap these mappings so that normal keyboard input maps to the user-enterable character.
- Modifies SpeciesName.cs to produce U+2024 for Mr. Mime in G1/G2.

Modify G1/G2 character mappings

---

PKHeX.Core/Legality/Verifiers/TrainerNameVerifier.cs
PKHeX.Core/PKM/Strings/StringConverter12Transporter.cs

Poké Transporter replaces OT names from the G1/G2 games with filtered words with a [language- and version-specific string](https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9_Transporter#Censored_words). Some of these names are too long for G1/G2: `クリスタル．` for JPN Crystal (6 > 5), `Crystal*` for ENG Crystal (8 > 7), etc. These names also all include characters that cannot be entered in G1/G2: `．` in Japanese, `*` in EFIGS, and `.` in Korean (this also applies to G3, but there isn't a legality check for G3 unavailable characters yet). 
This checks the OT name against the appropriate string given the Pokémon's language and version, and if it matches, prevents the `OT Name too long.` and `OT from Generation 1/2 uses unavailable characters.` messages from being displayed.

Fix Gen 1/2 VC filtered OT name legality

---

PKHeX.WinForms/Subforms/Save Editors/Gen5/SAV_Misc5.Designer.cs
PKHeX.WinForms/Subforms/Save Editors/Gen5/SAV_Misc5.cs
PKHeX.WinForms/Subforms/Save Editors/Gen9/SAV_Trainer9.Designer.cs
PKHeX.WinForms/Subforms/Save Editors/Gen9/SAV_Trainer9.cs

Gen 5 Misc Edits
- Fix duplicate unlock all musical props button caused by me
Gen 9 Trainer Editor
- Move Gender next to Trainer Name
- Group Blueberry Quests on Blueberry Tab
- Move Indigo Disk related unlock buttons to Blueberry Tab
- Disable Unlock All Buttons after operations

Gen 5 Misc and Gen 9 Trainer UI Edits

---

PKHeX.Core/Saves/SAV3.cs

It's 0xB9 in FRLG: https://github.com/pret/pokefirered/blob/master/src/event_data.c#L102

Fixed Pokedex National Unlock Magic for FRLG

---

PKHeX.WinForms/Subforms/ReportGrid.cs

Usually CSV files are saved with UTF-16 which is not easy to work with. This makes them UTF-8 without the BOM header by default, allowing them to be used more easily.

Make CSV files UTF-8 w/o BOM

---

PKHeX.Core/Saves/SAV2.cs

So you can actually set the players palette to another color.

Expose Gen 2 Palette to Block Editor

---

PKHeX.Core/Legality/Encounters/Templates/GO/EncounterSlot8GO.cs
PKHeX.Core/Legality/Encounters/Templates/Gen9/EncounterDist9.cs
PKHeX.Core/Legality/Encounters/Templates/Gen9/EncounterFixed9.cs
PKHeX.Core/Legality/Encounters/Templates/Gen9/EncounterMight9.cs
PKHeX.Core/Legality/Encounters/Templates/Gen9/EncounterOutbreak9.cs
PKHeX.Core/Legality/Encounters/Templates/Gen9/EncounterSlot9.cs
PKHeX.Core/Legality/Encounters/Templates/Gen9/EncounterStatic9.cs
PKHeX.Core/Legality/Encounters/Templates/Gen9/EncounterTera9.cs
PKHeX.Core/Legality/Encounters/Templates/Gen9/EncounterTrade9.cs
PKHeX.Core/Legality/Encounters/Templates/Shared/EncounterEgg.cs
PKHeX.Core/Legality/Verifiers/MiscVerifier.cs
PKHeX.Core/MysteryGifts/WC9.cs
PKHeX.Core/PKM/HOME/GameDataPK9.cs
PKHeX.Core/PKM/Interfaces/IObedienceLevel.cs
PKHeX.Core/PKM/Interfaces/Templates/IObedienceLevelReadOnly.cs
PKHeX.Core/PKM/PK9.cs
PKHeX.WinForms/Controls/PKM Editor/LoadSave.cs

Change from Obedience_Level  to ObedienceLevel since it was missed when other properties we changed to match C# naming standard.

Rename Obedience_Level To Match C# Naming Standard

---

PKHeX.Core/Saves/SAV4BR.cs

The player's current number of Poké Coupons in PBR is stored as an unsigned 24-bit integer. It is capped at 999,999 pts. normally (tested 9,999,998 + 975 = 999,999), but manually setting it to a value near 0xFFFFFF and gaining some more coupons will still cause it to overflow (tested 16,777,215 + 900 = 899).

Add PBR Poké Coupons accessor

---

PKHeX.Core/PKM/HOME/GameDataPK8.cs
PKHeX.Core/PKM/Strings/StringConverter8.cs

Follow-up on 08ed482 and https://github.com/kwsch/PKHeX/issues/4146#issuecomment-1877769156:
This maps the remaining (legal) symbols in the private use area that are modified on transfer from Bank -> HOME. If any of these replacements are made, any leading or trailing halfwidth spaces are trimmed. This can result in nicknames/OT names that are the empty string or consist entirely of fullwidth spaces, even though these can't normally entered.
I was unable to replicate how Anubis's Sudowoodo named `\uE0A5\uE0A3\uE0A4` (Zz, Right-up arrow, Right-down arrow) had its name changed to ` ` (one halfwidth space). I got an empty string instead--it's possible that behavior changed sometime between when those were transferred in 2021 and when I tested it in 2024.

Update how symbols are handled for Bank -> HOME transfers

---

PKHeX.Core/Saves/SAV3Colosseum.cs

Documents the flags/values that are set/modified in the Colosseum save file when receiving a gift from the Japanese Pokémon Colosseum Bonus Disc. These are mostly equivalent to their [GBA counterparts](https://github.com/kwsch/PKHeX/blob/ba7646e7a2dd62d747cd13fd934d1aba77d948ef/PKHeX.Core/Saves/SAV3.cs#L690), with the exception of `ReceivedAgetoGBA`, which is used to record how many of the 48 Celebi have been sent to a GBA game. The same offsets are affected in the USA and PAL region versions if the [leftover Bonus Disc content](https://tcrf.net/Pok%C3%A9mon_Colosseum/Bonus_Discs#Japanese_Bonus_Disc) is used.

Document JP Colosseum Bonus Disc gift flags

---

PKHeX.Core/PKM/SK2.cs
PKHeX.Core/PKM/Strings/StringConverter1.cs
PKHeX.Core/PKM/Strings/StringConverter2.cs
PKHeX.Core/PKM/Strings/StringConverter2KOR.cs
PKHeX.Core/Saves/SAV2Stadium.cs
PKHeX.Core/Saves/SAV_STADIUM.cs
PKHeX.Core/Saves/Substructures/Mail/Mail2.cs
PKHeX.Core/Saves/Substructures/Mail/MailDetail.cs
PKHeX.WinForms/Controls/SAV Editor/SAVEditor.cs
PKHeX.WinForms/Subforms/Save Editors/SAV_MailBox.Designer.cs
PKHeX.WinForms/Subforms/Save Editors/SAV_MailBox.cs

Japanese and Korean mail does not include the "nationality" field, and only store the author's name as 5 characters. The Korean encoding is double-byte, so both the message and author use twice as many bytes.
----
User-entered mail in Japanese/EFIGS always puts the line break in the same place, and pads it with 0x50 up to the end:
```
XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX 4E | line 1
XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX    | line 2
```
User-entered mail in Korean can have a line break anywhere in the first line. It still pads it with 0x50 up to the end if needed:
```
[No text entered]
59 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 | line 1
50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 …
```

Support G2 mail in all languages

---

PKHeX.WinForms/Subforms/SAV_Database.Designer.cs

The search button on the PKM Database window was hidden across multiple screen sizes. This adjusts the layout to closer match the display of windows like Encounter Database.

resize pkm database Table Layout Panel to unhide search button.

---

PKHeX.Core/Saves/SAV3.cs
PKHeX.Core/Saves/Substructures/Mail/Mail3.cs
PKHeX.WinForms/Subforms/Save Editors/SAV_MailBox.cs

International author names are padded with spaces to at least 6 characters ([decomp](https://github.com/pret/pokeemerald/blob/473e0623ba69541e6659ab88a5b9f35d94a3a76a/src/mail_data.c#L65)).
This means that the buffer will follow the pattern `[XX 00 00 00 00 00 FF] FF`.
In Japanese games, it's displayed in full using the Japanese font, not truncated like OT names/nicknames.
On display, it's treated as Japanese only if the name is 5 characters or less ([decomp](https://github.com/pret/pokeemerald/blob/473e0623ba69541e6659ab88a5b9f35d94a3a76a/src/international_string_util.c#L149)).
This means that the buffer will follow the pattern `[XX FF FF FF FF] FF 00 FF`.
Byte 6 is zero is due to the last two bytes of Japanese player names being zero, and byte 7 is always overwritten with a terminator.

Properly detect if G3 Mail is Japanese

---

PKHeX.Core/Saves/Access/ISaveBlock6Core.cs
PKHeX.Core/Saves/Access/SaveBlockAccessor6AO.cs
PKHeX.Core/Saves/Access/SaveBlockAccessor6AODemo.cs
PKHeX.Core/Saves/Access/SaveBlockAccessor6XY.cs
PKHeX.Core/Saves/SAV6.cs
PKHeX.Core/Saves/SAV6AO.cs
PKHeX.Core/Saves/SAV6AODemo.cs
PKHeX.Core/Saves/SAV6XY.cs
PKHeX.Core/Saves/Substructures/Gen6/FieldMoveModelSave6.cs
PKHeX.WinForms/Subforms/Save Editors/Gen6/SAV_Trainer.Designer.cs
PKHeX.WinForms/Subforms/Save Editors/Gen6/SAV_Trainer.cs
PKHeX.WinForms/Subforms/Save Editors/Gen7/SAV_Trainer7.Designer.cs
PKHeX.WinForms/Subforms/Save Editors/Gen7/SAV_Trainer7.cs
PKHeX.WinForms/Subforms/Save Editors/Gen7/SAV_Trainer7GG.Designer.cs

Basic support for editing the player's gender in Gen 6 without causing the game to hang on a black screen.
Note that the game seems to reset the player's appearance to the default if the saved appearance is for the other gender.
- In the FieldMoveModelSave block, the game writes an entry for the player tagged with 0x43 as the first byte.
- Within this entry at offset 0x8, there's a u16 that stores the model to display; this corresponds to the player's model.
- At least on maps where the corresponding model is present, some other values will actually load that model without a freeze (such as Shauna, Tierno, and Trevor in Vaniville/Route 1/Aquacorde).
- The game will regenerate this entry if it's missing, which is presumably why Gen 7 and later don't have this issue.
----
Since the existing …

Support G6/7 player gender editing

---

PKHeX.WinForms/Subforms/Save Editors/SAV_MailBox.cs

Catches Out Of Bounds error on ListBox SelectedIndex for when the B_PartyDown_Click event is triggered and the current Selection is in LB_PCBOX.

MailBox fix

---

PKHeX.Core/Legality/Verifiers/NicknameVerifier.cs
PKHeX.Core/Legality/Verifiers/TrainerNameVerifier.cs

pkmnclassic has recently had some pokemon traded that cause game crashes when viewing the pokemon's information, or when trying to remove the pokemon for these boxes. most of these pokemon were reported legal by pkhex however. this fixes the biggest use of these we've seen actively traded (some of the other checks require more validation, as they seemed to be buggy, we intend to validate those & send more PRs if needed).
this check effectively covers "NULL Bytes" within the trainers name, or the pokemon's nickname. We have attached an example pk4 that was traded through our service that exhibits this issue, a couple notes:
- Generation 5+ seem to not be affected and replace character names with '?'
- Not all screens crash inside of Generation 4, the big ones our users noticed were viewing …

validate nickname characters within gen4

---

PKHeX.Core/Legality/Encounters/Data/Live/EncounterServerDate.cs

- Campaign starts JST Friday, November 22, 2024, assuming stores open at 10:00am thus UTC-12 regions would be available on November 21, 2024
- The deadline for entering the serial code into the game is Saturday, May 31, 2025 at 23:59 hence latest redemption will be on Jun 1, 2025 at 02:59(UTC-12） 
- There are 2 version of wondercards being distributed and OT/Pokemon and Language locked to Korea (KOR) and Japan (JPN) but redeemable in any regions thus im unsure if i should apply the same date and include the KOR as well 
Wondercard 54, 55 & 56 - JPN
Wondercard 1011, 1012 & 1013 - KOR

Add Operation Get Mythical Keldeo, Zarude & Deoxys's date

---

PKHeX.Core/Legality/Encounters/Data/Live/EncounterServerDate.cs

- Korea's release and end date in-line with Japan.

Add Korea(KOR) Operation Get Mythical Keldeo, Zarude & Deoxys's date

---

PKHeX.Core/Legality/Encounters/Templates/Gen8a/EncounterSlot8a.cs

use pa8's current level for determining Mastered flag for Move Shop Records to ensure all flags are checked on encounters who learn moves close to their level mins

Encounter to PA8 generation tweak

---

PKHeX.Core/Legality/Encounters/Data/Live/EncounterServerDate.cs

- Pokémon Lucario & The Mystery of Mew Movie serial code distributed for those attending the movie's screening in South Korea from 22nd Jan 2025 1000 (UTC +9). Serial code redemption till 31th Mar 2025 2359 (UTC +9) hence date available for (UTC -12 ) regions would start from 21th Jan 2025 and end on 1st Apr 2025 for (UTC +12) regions

Add Pokémon Lucario & The Mystery of Mew Movie Gift KOR 아론's Lucario Date

---

PKHeX.Core/Legality/Verifiers/Ball/BallVerifier.cs
PKHeX.Core/MysteryGifts/WA8.cs
PKHeX.Core/MysteryGifts/WB8.cs

The WB8 and WA8 classes do not have properties for HeightScalar and WeightScalar, so a quirk in the code is needed to ensure correct entity generation and legality checks.
Additionally, Enamorus comes with a Cherish Ball rather than an LA-specific/proto ball, which also needs to be accounted for.

Handle generation and legality for HOME Manaphy and Enamorus

---

PKHeX.Core/MysteryGifts/WB7.cs

Unlike the previous China Mainland-exclusive wondercard (Meltan), Arbok has preset OT values for all languages. 
Although it is not legally possible to redeem this wondercard in any language other than CHS, PKHeX currently sets the `redeemLanguage` based on the active save file. This causes OT and Nickname info to be generated according to the save file’s language instead of CHS.
For Arbok, this results in it being generated with the Nickname flag on any non-CHS save. This can also cause problems for ALM, which fails to pull the correct encounter unless "Language: 9" is manually specified in the set.
Since this wondercard can only be redeemed on CHS save files, the `redeemLanguage` should always be CHS, not just the `language` of the generated entity.

Handle Arbok Mainland China wondercard

---

PKHeX.Core/Editing/Saves/Slots/Exporting/BoxExport.cs
PKHeX.Core/Editing/Saves/Slots/Exporting/BoxExportSettings.cs

Added a new setting to the box dumper to dump PKM prefixed with box indexes and slot indexes.

Added setting to export PKM with box and slot index

---

PKHeX.Core/Legality/Encounters/Data/Live/DistributionWindow.cs
PKHeX.Core/Legality/Encounters/Data/Live/EncounterServerDate.cs
PKHeX.Core/Legality/Verifiers/MiscVerifier.cs
PKHeX.Core/MysteryGifts/WA8.cs
PKHeX.Core/MysteryGifts/WB8.cs
PKHeX.Core/MysteryGifts/WC8.cs
PKHeX.Core/MysteryGifts/WC9.cs
PKHeX.WinForms/Controls/SAV Editor/SlotChangeManager.cs

Official redemption would be made possible on 7 Feb onward (if we uses NZDT +13 would mean 6 Feb for =＜ UTC+3 Time zone). Considering only a niche of users that would have access to a redemption code before 7 Feb( Kurt mentioned on 5 Feb (UTC+8) that redemption could be made at least possible on the 4 Feb but probably better to have a reasonable start date), making 5 Feb as a start date for those with access to the code early would be fair and within an acceptable tolerance. Redemption code for the distribution must be made by 30 June 2359 (PDT hence UTC+12 time zone would still be able to redeem it on the 1 Jul 2025.

Add Pokémon Day 2025 Flying Tera Type Eevee's date

---

PKHeX.Core/Util/DateUtil.cs

The function `IsTimeValid` checks if the received hour, minute, and second of the Pokémon is below 24, 60, and 60 respectively. For some reason the current code includes a "+1" for each check, which results in some legitimate Pokémon being marked as having an invalid timestamp.
Fixed edge cases:
- Received on the 23rd hour.
- Received on the 59th minute.
- Received on the 59th second.

Fix LGPE local time validation

---

PKHeX.Core/Legality/Verifiers/MiscVerifier.cs
PKHeX.Core/MysteryGifts/WB7.cs
PKHeX.Core/MysteryGifts/WC8.cs
PKHeX.Core/PKM/PB7.cs

The AbilityType for LGPE wondercards was hardcoded to 3, to ensure that the ability of generated entities was picked randomly (Any12). From what I’ve seen, the Meltan distributed via the HOME gift always has Ability 1. To make sure the first ability slot is always chosen during generation, the program needs to properly read the AbilityType from the wondercard. I’ve set the wondercard to contain AbilityType 0, so that 'OnlyFirst' is selected.
The handling for height, weight, and scale follows the same approach as the other classes.
Meltan is particularly tricky. The mystery gift stores the Souvenir Ribbon in the core data of the PH3. However, the WB7 and PB7 classes do not currently handle ribbons. It might be possible to utilize unused space within the WB7 and PB7 data, but the code flow …

Handle HOME Keldeo & Meltan; Revise WB7

---

PKHeX.Core/MysteryGifts/WB7.cs

Melmetal WC is 1502, filling the gap between Meltan (1501) and Arbok (1503). The [original announcement](https://m.weibo.cn/status/5088320474580186) implied that there would be three gifts, so that should be all of them.

Add Mainland China Melmetal gift

---

PKHeX.WinForms/Subforms/Save Editors/Gen4/SAV_Pokedex4.cs

fix #4420 
When the seen is not checked no forms should present to the seen side. 
This was causing some issues on save.

Pokedex - fix cannot unsee forms in Gen4

---

PKHeX.Core/Saves/SAV4.cs
PKHeX.Core/Saves/SAV4DP.cs
PKHeX.Core/Saves/SAV4HGSS.cs
PKHeX.Core/Saves/SAV4Pt.cs
PKHeX.Core/Saves/Substructures/Gen4/Group4.cs

Added a `Group4` class that mimics the Gen 4 games' group structure and allows editing groups in the block data window. Documented its locations and structure. This behavior is identical across all of the Gen 4 games.
When a new day is processed, group-derived data is recalculated:
- Group seeds are first updated to `(groupSeed * 0x6C078965) + 0x1` (ARNG)
- The active group seed is copied, unaltered, to the safari seed (DP: 0x72D0, Pt: 0x7F24, HGSS: 0x68A4) and the swarm seed (DP: 0x72D4, Pt: 0x7F28, HGSS: 0x68A8)
- The lotto number is calculated as `((groupSeed * 0x41C64E6D) + 0x3039) >> 16` and written to an event work address (DP: 0xE14, PT: 0xE24, HGSS: 0xE5C)
- A Battle Tower seed, which determines opponents in the Battle *Tower* only, is calculated as `(groupSeed * 0x5D588B65) + …

Implement Gen 4 groups and group-derived values

---

PKHeX.Core/Game/Enums/LanguageBR.cs
PKHeX.Core/Saves/SAV4BR.cs

For the PAL region, PBR appears to use a byte value to specify which language that save slot should be locked to. These values are English (0), German (1), Spanish (2), French (3), and Italian (4). NTSC-J/NTSC-U appear to ignore this value and leave it as zero.
For Japanese, there is an additional bit flag in the save file that needs to not be set for  the game to show the save data. NTSC-U/PAL have this flag set when creating a new save file, but they still read and display Japanese save files without the flag set normally.
When a save file is first created, it appears that PBR does not properly initialize the memory used for the save file, so whatever was in memory before is included in the second half of the save file. Previously, these saves would not be recognized since the checksum …

Add accessors for PBR save language

---

PKHeX.Core/Legality/Encounters/Data/Live/EncounterServerDate.cs

Submitting the date based on:
* Hard copy serial code issued at Pokémon Town 2025 with LOTTE event in Korea starting on April 25, 2025 at 10:00 AM (GMT+9) (operating hours beginning at 10:00 AM). Countries in UTC-11 would be able to redeem it on April 24, 2025 at 2:00 PM at the earliest.
* Event takes place at two locations:
- Lotte World Adventure: April 25 - May 18, 2025
- Jamsil Lotte World 2nd Floor (ZARA building): May 1 - May 6, 2025
* Serial code expiry date is June 30, 2025 at 23:59 (GMT+9) or July 1, 2025 in UTC+11

Add Korean Ditto Serial Code Distribution Event

---

PKHeX.WinForms/PKHeX.WinForms.csproj

Setting CETCompat to false in the project file resolves ntdll.dll crashes observed on .NET 9 Preview when OpenFileDialog's InitialDirectory points to deep paths like MyDocuments. This allows the application to run without triggering CET violations in this specific scenario.

Fix: Disable CETCompat to prevent crash with deep InitialDirectory

---

PKHeX.Core/Legality/Encounters/Templates/Gen9/EncounterDist9.cs
PKHeX.Core/Legality/Encounters/Templates/Gen9/EncounterMight9.cs
PKHeX.Core/Legality/Encounters/Templates/Gen9/EncounterTera9.cs
PKHeX.Core/Legality/Encounters/Templates/Gen9/ITeraRaid9.cs

Implement the IGenerateSeed32 interface for both the EncounterDist9 and EncounterMight9 templates, following the implementation patterns already present in EncounterTera9.

Standardize IGenerateSeed32 API for gen9 raid encounters

---

PKHeX.Core/Saves/SAV4BR.cs

- Previously, zeroed-out box names couldn't be edited. These checks are removed so that they can be read/written directly like they would be in any other game.
- Certain editors like SAV_BoxLayout clone the save file before editing it, but Clone did not preserve the currently selected save slot, meaning only slot 0 could be edited. Cloning now passes the selected slot as a parameter to the constructor.
- Play time uses the same structure as Western XD, a double with total seconds.

PBR: Fix box names, add play time

---

PKHeX.Core/Legality/Encounters/Data/Live/EncounterServerDate.cs

Serial code redemption starts on 7th Jun 2025, 1545 KST(UTC +9) hence UTC-8 regions onwards would be able to redeem it on 6th June 2025. Code must be redeemed by 9th Jun 2025 2359 KST(UTC +9), regions from UTC +10 onwards would be able to redeem it on 10th Jun 2025

 Add PTC 2025 홍주영's Porygon2's date

---

PKHeX.Core/Legality/Encounters/Data/Live/EncounterServerDate.cs

Mystery gift codes distributed via NFC scanning onsite at PJCS 2025 using Pokémon HOME and redeemed via Pokémon S/V on June 21, 2025 0900 JST(UTC +9), hence it is possible for regions from (UTC -1) and onwards to redeem it on June 20, 2025. Deadline for redemption by September 30, 2025 2359 JST(UTC +9), regions from (UTC +10) and onwards would be able to redeem it till October 1, 2025.

 Add PJCS 2025 Ray Yamanaka's Amoonguss date

---

PKHeX.Core/Saves/SAV1.cs
PKHeX.Core/Saves/Util/SaveLanguage.cs

This PR fixes the issue which current version of PKHeX is changing the Gen1 sav version from YW to RB in the fallback detection when the starter is not defined yet.
There is a secondary heuristic with Pikachu friendship for this case, which was not being used.
Also, removed the unnecessary bool field Yellow from SAV1, as we already have perfectly fine detection for RB and Yellow, so SAV.Version is trustworthy for any possible case.
This aligns with how the fallback detection works for Gen2 Crystal version.

Fix SAV1 fallback detection for Yellow version

---

PKHeX.Core/Saves/Util/SaveUtil.cs

Loading Japanese Crystal save files broke in ff0f472, the [previous logic](https://github.com/kwsch/PKHeX/blob/f370c0cc39bd12124e12c562cfe46acb5cda59d5/PKHeX.Core/Saves/Util/SaveUtil.cs#L295) required offsets 0x2D10 for GSC and 0x281A for Crystal (0x283E is for GS).

Fix JP Crystal save detection

---

PKHeX.Core/PKM/PK2.cs

Fixes regression that broke PK2 to PK1 conversion in f370c0c, only 0x1A bytes are supposed to be copied per the [previous implementation](https://github.com/kwsch/PKHeX/blob/0674d72fae0928c25a200739cd80f30e888407da/PKHeX.Core/PKM/PK2.cs#L117) and the [reverse process](https://github.com/kwsch/PKHeX/blob/e5705b078aed7c7af21e76bff816a5ae5f13b060/PKHeX.Core/PKM/PK1.cs#L164).

Fix PK2.ConvertToPK1

---

PKHeX.Core/Legality/Encounters/Data/Live/EncounterServerDate.cs

The earliest serial code distribution would be possible at EB Games outlets located in New Zealand, Wellington (UTC +13) on Sept 26, 2025 0900. Hence region in the (UTC <= +3) would be able to redeem it on Sept 25, 2025.  Code must be redeemed by Oct 23, 2025 2359 (UTC +9), this would allow regions in the UTC +10 onwards to redeem the code on Oct 24, 2025

 Add Shiny Miraidon / Koraidon Gift's date
