- Misc/ram2sav.cs
add starting position parameter to FindIndex
> Improve Magic Hunting.

- Misc/PKX.cs
- PKX/f1-Main.cs
- SAV/frmReport.Designer.cs
- SAV/frmReport.cs
Added Level to PKX class, and thus Box Data Report. Feature requested here: http://projectpokemon.org/forums/showthread.php?44969-Box-Data-Report-Level
> Add Level to Box Data Report

- README.md
https://github.com/kwsch/PKHeX/issues/49
> Explaining how building a binary

- Misc/PKX.cs
- PKX/f1-Main.cs
> Generate legal PID for Gen III Unown

- Legality/Checks.cs
- Legality/Tables.cs
- Ditto
- Most of the Undiscovered egg group
> Check for illegal hatched species

- Legality/Checks.cs
This boy can learn any HM move through Sketch so any memory regarding HMs is legal for him.
> Add Smeargle exception

- Misc/SAV5.cs
Pretty basic, but it should be functional, as I understand Gen V saves?
> Add basic Gen V Checksum Support

- Legality/Analysis.cs
- Program.cs
Did this on mobile, so sorry for the multiple commits lol
> Small Code Improvements

- MainWindow/Main.cs
- PKM/PKMConverter.cs
- PKM/ShowdownSet.cs
- Subforms/PKM Editors/MemoryAmie.cs
- Subforms/PKM Editors/Text.cs
- Subforms/Save Editors/Gen6/SAV_PokedexORAS.cs
- Subforms/Save Editors/Gen6/SAV_PokedexXY.cs
- Subforms/Save Editors/Gen6/SAV_Pokepuff.cs
- Subforms/Save Editors/Gen6/SAV_SuperTrain.cs
- Subforms/Save Editors/Gen6/SAV_Trainer.cs
- Subforms/Save Editors/SAV_Inventory.cs
- Subforms/frmReport.cs
If anything seems off or questionable, let me know. Built and everything functions as expected, main point of these are to prevent rare NPEs and improve code style.
> Final Set of Code Improvement Patches

- PKHeX/MainWindow/Main.cs
> Changed "Batte Video" to "Battle Video

- PKHeX/PKM/PK4.cs
I noticed my PPs had really weird values after transferring from PK4 to a SAV5 so I checked the code and found this little mistake. I believe this should fix the problem :)
> Fix for fix PPs in PK4 to PK5 conversion.

- PKHeX/MainWindow/Main.Designer.cs
- PKHeX/MainWindow/Main.cs
- PKHeX/MainWindow/Main.resx
- PKHeX/MainWindow/MainPK4.cs
- PKHeX/PKHeX.csproj
- PKHeX/PKM/BK4.cs
- PKHeX/PKM/PKM.cs
- PKHeX/PKM/PKMConverter.cs
- PKHeX/PKM/PKX.cs
- PKHeX/Saves/SAV1.cs
- PKHeX/Saves/SAV2.cs
- PKHeX/Saves/SAV3.cs
- PKHeX/Saves/SAV3RSBox.cs
- PKHeX/Saves/SAV4.cs
- PKHeX/Saves/SAV4BR.cs
- PKHeX/Saves/SAV5.cs
- PKHeX/Saves/SAV6.cs
- PKHeX/Saves/SaveFile.cs
- PKHeX/Saves/SaveUtil.cs
- PKHeX/Subforms/Save Editors/SAV_BoxViewer.cs
Initial support for Pokemon Battle Revolution save files.
> PBR support

- PKHeX/PKM/CK3.cs
Untested, but logically seems correct. I wouldn't doubt you've got a similar commit lined up locally, but this in case you do not.
Closes #374.
> CK3: Fix mixed up party stats

- PKHeX/Resources/text/ko/lang_ko.txt
* Translated from latest English language file.
It has further improvement on readability and
I've fixed lots of weird words/sentences.
* Use official translations for ribbons (from HGSS)
> Improve Korean language

- PKHeX/PKHeX.csproj
- PKHeX/PKM/PKX.cs
> Revert "Mono fix"

- PKHeX/MainWindow/Main.cs
> Show gamesync gen7

- PKHeX/Saves/SAV7.cs
Fix FestaCoins
0x50D08 ... Current coins
0x50D0C ... Total coins
0x69C98 ... Used coins
total = current + used
> Fix FestaCoins

- PKHeX/Subforms/SAV_Database.cs
Extending 8b274ddbc35e810608744d47c1bb873682b4d3b6
Changes and their reasoning:
- Used a concurrent bag inside Parallel.ForEach to avoid potential overhead of `lock`.
- Removed `RawDB.Where(pk => pk != null)` because the Parallel.ForEach lambda handles this check
- Because LINQ extension methods' execution is deferred, it's best to wait to create a list until it's needed, so the extension methods were changed together without creating intermediate lists.
A basic speed comparison using VS's diagnostic tools was inconclusive, possibly indicating any speed difference either way is negligible.
> More database speed improvements

- PKHeX/Properties/Resources.resx
Will merge once automated build passes
> Fixed case sensitivity

- PKHeX/Legality/Checks.cs
This is my attempt to fix the Giratina's form issue (#792). I'm currently trying to fix the Arceus forms too (and maybe  I'll do the Silvally forms too)
> Fix legality on form change with held item

- PKHeX.WinForms/Util/NetUtil.cs
- PKHeX/MysteryGifts/PGT.cs
No functional differences, just better class typing.
> Class consistency fixes

- PKHeX.WinForms/MainWindow/Main.cs
Should resolve #833.
This is why I prefer if statement logic to return statements littered everywhere.
> Fixed settings not saving when form closes

- PKHeX/Legality/Tables7.cs
Reference: https://github.com/kwsch/PKHeX/issues/895
> Additional G7 Unreleased Items

- PKHeX.WinForms/Subforms/Save Editors/Gen7/SAV_PokedexSM.Designer.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen7/SAV_PokedexSM.cs
Fixed: Wishiwashi schoolForm will be checked when use allModifying button.
Show mons by formName, I think it will be easier to observe the dex data.
> add FormList to Gen7 Pokedex Editor 

- PKHeX.WinForms/Subforms/Save Editors/Gen7/SAV_Trainer7.Designer.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen7/SAV_Trainer7.cs
- PKHeX/Saves/SAV7.cs
I have confirmed, the saved value(0 to 31) exactly adapt to form value of Scatterbug's egg.
> add Vivillon FormValue

- PKHeX/PKM/PK3.cs
Fixes gen 3 egg name so it always says Egg in japanese.  Also fixes language so it is always 0x601.
> Fixes gen 3 egg name and language.

- PKHeX.WinForms/Subforms/Save Editors/Gen7/SAV_Trainer7.Designer.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen7/SAV_Trainer7.cs
- PKHeX.WinForms/Util/PKMUtil.cs
- PKHeX/Saves/SAV7.cs
The Refresh value countup at 0:00AM, max255, will be 0 when start refresh.
If the value was 5 or more, the mon looks sad.
> tip for stats,value about Refresh,small fix.

- PKHeX/MysteryGifts/WC6.cs
- PKHeX/MysteryGifts/WC7.cs
- HP IV should not be fixed
- actual shiny lock in game
> Fix WC to PKM Converter

- PKHeX/Legality/Tables4.cs
Please let me know if the format is correct
> Update EncounterInfo for Gen4

- PKHeX/Legality/Tables4.cs
> Add EncounterStatic for DPPt

- PKHeX/Legality/Core.cs
- PKHeX/Legality/Tables4.cs
Sorry I don't know the SID of in-game trade pokemon, just leave it 00000
> Add gen4 TradeGift & TMHM Table

- PKHeX/Legality/Tables3.cs
- PKHeX/Legality/Tables5.cs
- add gen5 table
- fix gen3 snorlax location
I will go over gen3-5 later to see if there is other typo
> Add gen5 EncounterStatic

- PKHeX/Legality/Tables3.cs
- PKHeX/Legality/Tables4.cs
- PKHeX/Legality/Tables5.cs
- Add emerald roaming PKM
- Fix version exclusive about Tornadus/Thundurus
- Add HGSS Togepi egg move
- Add N' Zorua met location
- Misc species ID location ID and Met_Level fixes
> Misc table fixes

- PKHeX/Legality/Tables4.cs
- PKHeX/Legality/Tables5.cs
- gen5 from bulbapedia
- hgss from RNGtool
- dppt needs research (I will look into it together with gen3)
- Some formatting
> Add gen4/5 roaming PKM locations

- PKHeX.WinForms/Subforms/Save Editors/Gen4/SAV_Pokedex4.Designer.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen4/SAV_Pokedex4.cs
- PKHeX/Saves/SAV4.cs
mismatch of formFlag, and languageFlag also fixed.
full edit of DexUpgrade added.
DP,with SetToSavOption, some mons otherLangDexFlag will be edit.
> fix gen4dex forms

- PKHeX.WinForms/Util/NetUtil.cs
Shouldn't cause any compiler issues.
> Fix Typo in NetUtil

- PKHeX.WinForms/Subforms/Save Editors/Gen7/SAV_Trainer7.Designer.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen7/SAV_Trainer7.cs
- PKHeX/Saves/SAV7.cs
Some function has already included in SAV7, but no controls?
Add function about BallThrow Flags.
> Add controls of G7Stamp,BallThrow

- PKHeX.WinForms/Subforms/Save Editors/Gen7/SAV_Trainer7.Designer.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen7/SAV_Trainer7.cs
- PKHeX/Saves/SAV7.cs
Not checked for legality(e.g.MaxStreaks)
> Add G7BattleTree Supers Unlock

- PKHeX.WinForms/Subforms/Save Editors/Gen7/SAV_Trainer7.Designer.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen7/SAV_Trainer7.cs
- PKHeX/Saves/SAV7.cs
This checkbox just unlock the MegaButton in battle.
I have tested wildPokemon battle, not checked about InternetBattle.
> Add Gen7 Mega unlock

- PKHeX.WinForms/MainWindow/Main.cs
- PKHeX.WinForms/PKHeX.WinForms.csproj
- PKHeX.WinForms/Subforms/Save Editors/Gen4/SAV_Misc4.Designer.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen4/SAV_Misc4.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen4/SAV_Misc4.resx
- PKHeX/Saves/SAV4.cs
there is now only a tab Poketch.
> add Gen4 MiscEditForm

- PKHeX.WinForms/Subforms/Save Editors/Gen4/SAV_Misc4.Designer.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen4/SAV_Misc4.cs
- PKHeX/Saves/SAV4.cs
drag&drop will import file, click will edit directly.
> Poketch DotArtEdit

- PKHeX.WinForms/Subforms/Save Editors/Gen3/SAV_Misc3.Designer.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen3/SAV_Misc3.cs
- PKHeX/Saves/SAV3.cs
- PKHeX/Saves/SaveUtil.cs
hesitated that treat the islands as ferry destination, or as island and include Mirage Island.
> add for gen3

- PKHeX.WinForms/Subforms/Save Editors/Gen3/SAV_Misc3.Designer.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen3/SAV_Misc3.cs
- PKHeX.WinForms/Subforms/Save Editors/SAV_SimpleTrainer.cs
- PKHeX/Saves/SAV3.cs
All address is JapaneseVer.ROM(Em,FR), also need check with InternationalVer.
> adds for Gen3

- PKHeX.WinForms/MainWindow/Main.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen4/SAV_Misc4.Designer.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen4/SAV_Misc4.cs
- PKHeX/Saves/SAV4.cs
Editable many values. It seems a batch button needs,
but little demand, I have not made it.
> add G4 BattleFrontier controls

- PKHeX.WinForms/Subforms/Save Editors/Gen4/SAV_Misc4.cs
> fix G4 Miscs

- PKHeX.Core/Legality/Tables7.cs
Released via international serial code "AZUL"
> Unban Heracronite and Houndoominite

- PKHeX.Core/Properties/Resources.Designer.cs
- PKHeX.Core/Properties/Resources.resx
- PKHeX.Core/Resources/text/other/const_dp.txt
- PKHeX.Core/Resources/text/other/flags_dp.txt
- PKHeX.Core/Saves/SAV4.cs
- PKHeX.WinForms/Subforms/Save Editors/SAV_EventFlags.cs
This resources include some flags, not all,
that be changed when defeated/captured in game,
but sufficient to repop.
> add EventFlags resources DP

- README.md
Previously did not mention formats for:
- SAV3Colosseum
- SAV3XD
- SAV4BR
> Update formats included in README.md

- PKHeX.Core/Properties/Resources.Designer.cs
- PKHeX.Core/Properties/Resources.resx
- PKHeX.Core/Resources/text/other/const_dp.txt
- PKHeX.Core/Resources/text/other/const_hgss.txt
- PKHeX.Core/Resources/text/other/flags_dp.txt
- PKHeX.Core/Resources/text/other/flags_hgss.txt
- PKHeX.Core/Saves/SAV4.cs
- PKHeX.WinForms/Subforms/Save Editors/SAV_EventFlags.cs
Fix DP for consistency.
(now all DP&HGSS flag/const position number is same as in game used)
Checked with HG. SS not checked. (Groudon flag unknown)
> add EventFlags resources HGSS

- README.md
macOS is the new official name for OS X
> Update OS X to macOS

- PKHeX.Core/Properties/Resources.Designer.cs
- PKHeX.Core/Properties/Resources.resx
- PKHeX.Core/Resources/text/other/const_bw.txt
- PKHeX.Core/Resources/text/other/flags_bw.txt
- PKHeX.Core/Saves/SAV5.cs
- PKHeX.Core/Saves/SaveFile.cs
- PKHeX.WinForms/Controls/SAV Editor/SAVEditor.cs
- PKHeX.WinForms/PKHeX.WinForms.csproj
- PKHeX.WinForms/Subforms/Save Editors/Gen5/SAV_Misc5.Designer.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen5/SAV_Misc5.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen5/SAV_Misc5.resx
- PKHeX.WinForms/Subforms/Save Editors/SAV_EventFlags.cs
I recently noticed that some activation use TID/SID,
I will re-check past resources that have abnormal value(e.g.AzureFlute),
after researching BW2,Pt.
> add EventFlags resources BW

- PKHeX.WinForms/Controls/SAV Editor/SAVEditor.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen5/SAV_Misc5.Designer.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen5/SAV_Misc5.cs
I excepted first 8 keys(used for check selected value),
they are very easy to edit in game.
> add BW2 KeySystem Unlock

- PKHeX.Core/Saves/SAV5.cs
ExportSAV without changes will become export same data.
> Fix BW2 checksum offset

- PKHeX.Core/Properties/Resources.Designer.cs
- PKHeX.Core/Properties/Resources.resx
- PKHeX.Core/Resources/text/other/const_b2w2.txt
- PKHeX.Core/Resources/text/other/flags_b2w2.txt
- PKHeX.WinForms/Subforms/Save Editors/Gen5/SAV_Misc5.Designer.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen5/SAV_Misc5.cs
- PKHeX.WinForms/Subforms/Save Editors/SAV_EventFlags.cs
Funfest Mission titles refer to bulbapedia funfest page.
> add BW2 resources

- PKHeX.WinForms/Subforms/Save Editors/Gen3/SAV_Misc3.Designer.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen3/SAV_Misc3.cs
I don't know why Chimecho is listed at the very end.
> add FRLG TrainerCard PokemonIcons

- PKHeX.Core/Properties/Resources.Designer.cs
- PKHeX.Core/Properties/Resources.resx
- PKHeX.Core/Resources/text/other/const_pt.txt
- PKHeX.Core/Resources/text/other/flags_dp.txt
- PKHeX.Core/Resources/text/other/flags_hgss.txt
- PKHeX.Core/Resources/text/other/flags_pt.txt
- PKHeX.Core/Saves/SAV4.cs
- PKHeX.WinForms/Controls/SAV Editor/SAVEditor.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen4/SAV_Misc4.Designer.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen4/SAV_Misc4.cs
- PKHeX.WinForms/Subforms/Save Editors/SAV_EventFlags.cs
add missing FlyDst and use MetLocation string.
add TrainerCard flags to FlagEditor.
add Pt resources.
fix HoneyTree, the BlockOffset needed.
> fix Gen4 Misc Resources

- PKHeX.Core/Saves/SaveUtil.cs
- PKHeX.WinForms/MainWindow/Main.cs
- PKHeX.WinForms/Util/PathUtilWindows.cs
- PKHeX.WinForms/Util/WinFormsUtil.cs
I also added comments where appropriate, because it took far too long to understand what was going on when reviewing the commit that fixed the original bug.
> Fixed another potential blank error message

- PKHeX.Core/Legality/Tables4.cs
Resolves the first bug listed in #1297. Thanks @javierhimura for pointing this out!
> Fix Old Chateau encounter type

- PKHeX.Core/Legality/Tables7.cs
https://twitter.com/PokemonLegality/status/881769237454487555
https://twitter.com/PokemonLegality/status/882097809322893312
> Unban various Held Items

- PKHeX.Core/Legality/Encounters/EncounterGenerator.cs
Resolves the 4th bug listed in #1297. Thanks @kwsch for providing the code!
> Manaphy Egg fixes

- PKHeX.Core/Legality/Encounters/EncounterGenerator.cs
- PKHeX.Core/Legality/Tables3.cs
- PKHeX.Core/MysteryGifts/WC3.cs
Fixes various gen 3 event templates.
> Fixes various gen 3 event templates.

- PKHeX.Core/Legality/Tables3.cs
> Fixes WC3 eggs.

- PKHeX.Core/Legality/Tables3.cs
> Fixes & Adds Gen 3 Events

- PKHeX.Core/Legality/Core.cs
> Fixed Zygarde Legalities from Gen 6 origin

- PKHeX.Core/Legality/Tables7.cs
https://twitter.com/SerebiiNet/status/888263376853286912
> Unban Aggronite

- PKHeX.Core/Legality/Encounters/Data/Encounters4.cs
D/P, not B/W :p 
Resolves #1375
> Fix D/P static encounter fetch

- PKHeX.Core/Resources/text/other/flags_oras.txt
Added Eon Ticket flag :)
Also, I'm new to the site - do I have to create a pull request before a file can be changed?
> Update for flags_oras.txt

- PKHeX.Core/Saves/SAV4.cs
- PKHeX.WinForms/Controls/SAV Editor/SAVEditor.Designer.cs
- PKHeX.WinForms/Controls/SAV Editor/SAVEditor.cs
- PKHeX.WinForms/Controls/SAV Editor/SAVEditor.resx
- PKHeX.WinForms/PKHeX.WinForms.csproj
- PKHeX.WinForms/Subforms/Save Editors/Gen4/SAV_Underground.Designer.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen4/SAV_Underground.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen4/SAV_Underground.resx
Hi! 
I've been looking for some Underground Score offsets through the Internet, I found them (atleast Pt ones, but I believe these are the same in DP) in [PP](https://projectpokemon.org/forums/forums/topic/14637-some-research-in-nds-save-files/) and wanted to put them in so everyone can edit their ones. 
I really think this could be written really better, because, for some reasons I don't get, when I'm trying to import the modified save, it says it's corrupted, yet by manually hex-editing the values and then fixing the checksums with PKHeX I managed to import the save properly (succeeded one time in my various attempts).
I'm opening the PR with all I've done, I hope I did not break anything else tho... sorry for my inexperience.
Here's a pic about what I've achieved
> Underground Score Editor (help needed)

- PKHeX.WinForms/Controls/SAV Editor/SAVEditor.cs
I did not know this, sorry! I fixed my entirely mistake here
> Fix Underground button to be only enabled for DPPt

- PKHeX.WinForms/Util/PathUtilWindows.cs
> Add GodMode9 3DS backup path

- PKHeX.WinForms/Util/PathUtilWindows.cs
For those using Rosalina and JKSM :)
> Add JKSM backup path

- PKHeX.WinForms/Program.cs
Add the ability to log error details to a file if there's an error displaying error details
> Add emergency exception handling

- PKHeX.WinForms/Util/PathUtilWindows.cs
Adds support for [Checkpoint save manager](https://github.com/BernardoGiordano/Checkpoint). Supports NDS and 3DS save data!
> Add Checkpoint save detection

- PKHeX.Core/MysteryGifts/MysteryGift.cs
- PKHeX.Core/MysteryGifts/PGT.cs
- PKHeX.WinForms/Subforms/SAV_MysteryGiftDB.Designer.cs
- PKHeX.WinForms/Util/WinFormsUtil.cs
Adds WC4 support through same detection as PK4 vs EK4.
> Adds WC4 support

- PKHeX.Core/Legality/Encounters/Data/Encounters7.cs
- Cresselia
- Swanna
- Drapion
- Audino
- Medicham
- Magcargo
- Quagsire
Working on getting a lot of these.
> Add several Ultra Warp Ride locations

- PKHeX.Core/Legality/Encounters/Data/Encounters7.cs
Whoops, was about to add the Ditto 5 too.
Edit: I think it's safe to assume all the normal Pokemon will have 222 as location.
> Normal Pokemon @ Ultra Space Wilds / Sandygast @ Route 15

- PKHeX.Core/PKHeX.Core.csproj
- PKHeX.Core/Resources/text/script/flags_usum_en.txt
> Add USUM Legendary re-battle flags

- PKHeX.WinForms/Subforms/Save Editors/Gen7/SAV_Trainer7.Designer.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen7/SAV_Trainer7.cs
for USUM. have not checked with SM, but I think it works.
> add G7 MapUnmask & FlyDestination

- PKHeX.Core/Resources/text/script/flags_usum_en.txt
SlidePad will be enabled from the first play.
> add UltraRide SlidePad flag

- PKHeX.WinForms/Subforms/Save Editors/Gen7/SAV_ZygardeCell.cs
Who is that Pokemon...Steelix!
> fix Sticker location

- PKHeX.Core/Legality/Checks.cs
Related:
https://projectpokemon.org/home/forums/topic/42528-bw2-in-game-trades-yancycurtis-20171117/
> Flip Valid Trade OT Compare Operator

- PKHeX.Core/Legality/Tables7.cs
> Unban white/orange Flabebe HA

- PKHeX.Core/Saves/SAV7.cs
- PKHeX.WinForms/Controls/SAV Editor/SAVEditor.Designer.cs
- PKHeX.WinForms/Controls/SAV Editor/SAVEditor.cs
- PKHeX.WinForms/PKHeX.WinForms.csproj
- PKHeX.WinForms/Subforms/Save Editors/Gen7/SAV_FestivalPlaza.Designer.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen7/SAV_FestivalPlaza.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen7/SAV_FestivalPlaza.resx
There are too many phrases,
I have no plan to complete all list of phrases.
But I think user can edit phrases of each facility
by using their phrase settings.
> add G7 FestivalPlaza Editor

- PKHeX.WinForms/Subforms/Save Editors/Gen7/SAV_FestivalPlaza.Designer.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen7/SAV_FestivalPlaza.cs
> add ListBox to FestaPlazaEdit

- PKHeX.WinForms/Subforms/Save Editors/Gen7/SAV_FestivalPlaza.Designer.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen7/SAV_FestivalPlaza.cs
When the facility is NOT introduced with visitors
and start FestaPlaza after latest started date,
VisitorFesID become unknown small value.(0/5/7/9/11)
So I stop auto-deletion of visitor data.(and put delete button)
> fix FestaPlazaEdit value

- PKHeX.WinForms/Subforms/Save Editors/Gen7/SAV_FestivalPlaza.Designer.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen7/SAV_FestivalPlaza.cs
the NOTE(Giovanni alert) is a little excessive I think,
I will remove it after detect a list of upcoming trainers.
> add USUM BattleAgency control

- PKHeX.Core/Legality/Tables7.cs
- Ban all fossils in beast ball
> ban beast ball fossils

- PKHeX.Core/PKHeX.Core.csproj
- PKHeX.Core/Resources/text/script/flags_c_en.txt
- PKHeX.Core/Saves/SAV2.cs
- PKHeX.WinForms/Subforms/Save Editors/SAV_EventFlags.cs
> add Crystal GS EventFlags

- PKHeX.Core/Legality/RNG/Frame/Frame.cs
> Fix level check compare

- PKHeX.Core/PKM/PK3.cs
- PKHeX.Core/PKM/PK4.cs
- PKHeX.WinForms/Controls/SAV Editor/SAVEditor.Designer.cs
- PKHeX.WinForms/Controls/SAV Editor/SAVEditor.cs
- PKHeX.WinForms/PKHeX.WinForms.csproj
- PKHeX.WinForms/Subforms/Save Editors/SAV_MailBox.Designer.cs
- PKHeX.WinForms/Subforms/Save Editors/SAV_MailBox.cs
- PKHeX.WinForms/Subforms/Save Editors/SAV_MailBox.resx
I just wanted to fix PK3 heldMailID.
> add MailBox Editor

- PKHeX.WinForms/Subforms/Save Editors/SAV_MailBox.cs
fix Gen4 Controls
add Mail .Empty for LegalCheck
add Mail SetBlank() for make BlankMail
> fix MailBoxEditor

- PKHeX.Core/Legality/Encounters/Data/Encounters7.cs
good job Game Freak https://twitter.com/wwwwwwzx/status/961057063198539778
> Allow shiny Partner Cap Pikachu

- PKHeX.WinForms/Controls/PKM Editor/PKMEditor.cs
https://github.com/kwsch/PKHeX/issues/1854#issuecomment-369270152
> Fix Inverted Max PP Shortcut

- PKHeX.Core/Legality/Tables7.cs
HA Starters Event via Pokemon Bank
> Unban Gen 7 Starters HA

- PKHeX.WinForms/Controls/PKM Editor/PKMEditor.cs
- PKHeX.WinForms/Controls/PKM Editor/StatEditor.cs
- Pass HaX to StatEditor once everything else loads
- Fix Hacked Stats enabled check
Round 2 of https://github.com/kwsch/PKHeX/pull/1867
> Fix HaX Mode

- PKHeX.Core/PKM/ShowdownSet.cs
Edge cases with `-F` as forms are already handled in the code. fixes #1905
> Fix Meowstic edge case

- PKHeX.WinForms/Controls/SAV Editor/Sorter.cs
For clarity's sake.
[lol](https://twitter.com/wernt0/status/988091216209305600)
> Update sort menu labels

- PKHeX.WinForms/Controls/SAV Editor/Sorter.cs
https://github.com/kwsch/PKHeX/commit/4b6ee3fbf5bb261069757a635fa5126a94c3ada1#commitcomment-28822553 ;)
> Add Past Generation deleter

- PKHeX.Core/Legality/Checks.cs
- PKHeX.Core/Legality/Evolutions/EvolutionTree.cs
- PKHeX.WinForms/Subforms/Save Editors/SAV_Wondercard.cs
30: level + dark type in the party
32: level + day
33: level + night
34: level + female
Note Meowstic isn't affected due to another entry of level + male (23)
> Fix minlevel of Pangoro/Tyrantrum/Aurorus in gen6

- PKHeX.WinForms/Controls/SAV Editor/SlotChangeManager.cs
Tested and it's working fine now. Resolves #2118.
> Fix alt form cries from not playing

- PKHeX.Core/Legality/Encounters/Data/Encounters6.cs
> Add XY Magikarp trade IVs

- PKHeX.Core/Resources/text/script/flags_bw_fr.txt
- PKHeX.Core/Resources/text/script/flags_oras_fr.txt
Aaaaaand here comes yet another round of french GUI updating.
Question, do you have a Discord, by any chance?
> Add French translations for ORAS, BW flags

- PKHeX.Core/Saves/Storage/SAV4Ranch.cs
- PKHeX.Core/Saves/Util/SaveUtil.cs
I don't know yet if the OT offset is the same though
> add offsets & save-size for ranch's platinum update

- PKHeX.Core/Legality/Tables7b.cs
https://twitter.com/serebiinet/status/1088771077780709376
https://twitter.com/LeekDuck/status/1095835736723599360
> Update GO shinies

- README.md
> Add file references for Let's Go

- PKHeX.Core/Saves/Substructures/Battle Videos/BV7.cs
The parsing logic was copied from BV6, and just the offsets updated for Gen 7. I've only tested this against Battle Video files generated by Ultra Moon, so I'm honestly not sure if the non-Ultra games Battle Videos are any different.
Let me know if you'd like me to do any refactoring of the copied code from BV6 so it can be shared between the two classes, or if I should pursue additional testing, thanks!
> Add PlayerNames and MatchStamp to BV7

- PKHeX.Core/Legality/Tables7b.cs
Bug event! https://twitter.com/SerebiiNet/status/1113174255666180102
> Update GO shiny banlist

- PKHeX.Core/PKM/Util/PKMConverter.cs
> Fix PKM conversion prompt order

- PKHeX.Core/Legality/Tables/Tables7b.cs
anotha one https://twitter.com/SerebiiNet/status/1118752855119355905
> Unban GO Shiny Lapras

- PKHeX.Core/Legality/Tables/Tables7b.cs
https://twitter.com/LeekDuck/status/1123688704906813442
> Unban Shiny Seel

- PKHeX.Core/PKHeX.Core.csproj
Explicitly target LangVersion 7.2.
> Fix C# 7.2 Build Error

- PKHeX.WinForms/PKHeX.WinForms.csproj
Explicitly target LangVersion 7.2.
> Fix WinForms C# 7 targeting

- PKHeX.Core/Legality/Tables/Tables7b.cs
Just wanna Pokémon GO ahead and get this out of the way
> Unban GO Shiny Onix

- PKHeX.Core/Legality/Encounters/Data/Encounters4.cs
- PKHeX.Core/Legality/Encounters/Data/Encounters5.cs
- PKHeX.Core/Legality/Encounters/Data/Encounters6.cs
- PKHeX.Core/Legality/Encounters/Data/Encounters7.cs
Fix typos (that I found), reorganize some encounters and clean up some order for style consistency.
Might've missed some things but this covers a majority of it ;)
> Encounters cleanup

- PKHeX.WinForms/Subforms/Save Editors/Gen5/SAV_Misc5.cs
Was missing some GameVersion checks.
> Fixed crash of Gen 5 Misc Editor

- PKHeX.Core/Saves/SAV6XY.cs
> Remove check for impossible condition in XY Save

- PKHeX.Core/Resources/text/script/const_e_en.txt
- PKHeX.Core/Resources/text/script/const_frlg_en.txt
- PKHeX.Core/Resources/text/script/flags_frlg_en.txt
Just to be sure - please check that my edits don't break the program (I assumed the file format by looking at others, and have no knowledge of how it interacts with the GUI!)
> FR/LG: More variables!

- PKHeX.Core/Legality/Encounters/Data/Encounters3.cs
https://github.com/kwsch/PKHeX/issues/2367
> Add Realgam Tower to Colosseum Encounters

- PKHeX.Core/Legality/Tables/Tables7b.cs
https://twitter.com/serebiinet/status/1158060434467033089
> Unban GO Shiny Poliwag

- PKHeX.Core/Saves/SAV2.cs
> Fix Gen. 2 key items and balls

- PKHeX.Core/Legality/Encounters/Data/Encounters8.cs
All Eeveelutions spawns at the Lake of Outrage, based on the weather?
> Add Eevveelutions Spawns for Lake of Outrage

- PKHeX.Core/Legality/Encounters/Data/Encounters8.cs
- Removed version lock on Motostoke Stadium Vulpix (may want to investigate Growlithe)
- Wild Area Updates
- Other Static Updates
> Static Locations Update

- PKHeX.Core/Saves/SAV4HGSS.cs
- PKHeX.Core/Saves/SAV4Sinnoh.cs
> Add G4 Box Flags

- PKHeX.Core/Legality/Encounters/Data/Encounters8Nest.cs
https://serebii.net/swordshield/maxraidbattles.shtml
> modify nest locations based on serebii

- PKHeX.Core/Legality/Encounters/Data/Encounters8Nest.cs
- PKHeX.Core/Legality/Encounters/EncounterStatic8N.cs
Separate PR from the one I posted since you can separately merge this if you have an alternate solution for #2489 
This change is based on a lot of experimentation done in my discord.
> Misc Nest Fixes

- PKHeX.Core/Legality/Encounters/Data/Encounters8.cs
Lapras Spawns in Area 1:
North/East/South/West Lake Miloch, 
Area 2:
the Lake of Outrage (in a Wild Area)
> Add Multiple Lapras Spawns

- PKHeX.Core/Legality/Encounters/Data/Encounters8.cs
> Also Seaking have multiple Locations

- PKHeX.Core/Legality/Encounters/Data/Encounters8.cs
Vanilluxe spawns also on any Lake if its snowing
> Add Vanilluxe Multiple Encounters

- PKHeX.Core/Legality/Tables/Tables8.cs
https://www.serebii.net/swordshield/items.shtml
only Pixie Plate & Normal Gem are in the Game yet.
> Update Unreleased Items(SwSh)

- PKHeX.Core/Legality/Structures/Shiny.cs
> comment typo fix

- PKHeX.Core/Legality/Encounters/Data/Encounters8.cs
- PKHeX.Core/Legality/Verifiers/TransferVerifier.cs
> Add more Gen 8 static encounter locations

- PKHeX.Core/Saves/SAV8.cs
- PKHeX.Core/Saves/SaveFile.cs
- PKHeX.Core/Saves/Substructures/Gen8/MyStatus8.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen8/SAV_Trainer8.Designer.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen8/SAV_Trainer8.cs
Append option to change watt value
> Add watt to trainer data editor

- PKHeX.Core/Legality/Encounters/Data/Encounters8.cs
Closes #2589 
https://bulbapedia.bulbagarden.net/wiki/In-game_trade#Sword_and_Shield
> Legality: Add Nature and Gender to Gen 8 Trades

- PKHeX.Core/Editing/ShowdownSet.cs
smogon allows Dusk Mane as well as Dusk-Mane as their form argument
> sanity check necrozma forms

- PKHeX.Core/Legality/Tables/Tables.cs
**Please describe your improvement.**
Adds the SwSh legends to the tables.
> Add SWSH Legends to the Tables

- PKHeX.Core/Saves/Substructures/Gen5/BattleSubway5.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen5/SAV_Misc5.Designer.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen5/SAV_Misc5.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen5/SAV_Misc5.resx
Adding some initial changes to edit values of the Subway Scores. Currently only available for Black and White, I still have to figure out if the offsets are the same at all on B2W2...
This could have been coded better tho...
> Add Subway Scores edition

- PKHeX.Core/Legality/Encounters/Data/Encounters3.cs
Had a bunch of them and they were flagged because of the moves
> Fix Seedot and Nuzleaf swarm moves

- PKHeX.Core/Saves/Substructures/Gen5/BattleSubway5.cs
> Fix Subway Super checks

- PKHeX.Core/Saves/SAV4Sinnoh.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen4/SAV_Underground.Designer.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen4/SAV_Underground.cs
Thought I had to correct this after having a look at it!
> Miscelanous fix on Underground Scores

- PKHeX.WinForms/Program.cs
I'm tired of seeing people being tired of seeing people getting this error and not looking it up.
> Add check for old PKHeX.Core.dll

- PKHeX.WinForms/Subforms/Save Editors/SAV_Wondercard.Designer.cs
- PKHeX.WinForms/Subforms/Save Editors/SAV_Wondercard.cs
pressing the delete key on the received items list will delete the selected item(s)
multi-selection of received mystery gifts for mass deletion
improved index selection on the deletion of any mystery gift(s)
tab indexing, my favorite pastime
> quality of life improvements on the mystery gift form

- PKHeX.Core/Legality/Verifiers/FormVerifier.cs
> fix yamask/runerigus form argument handling

- PKHeX.Core/Saves/Substructures/Gen8/TrainerCard8.cs
https://github.com/kwsch/PKHeX/commit/a1ae14325a41b9bfdebd4ca6a2ada538725cd02f#commitcomment-37103852
> Correct Day offset

- PKHeX.Core/Legality/Tables/Locations.cs
> Change FRLG hatch location

- PKHeX.Core/Legality/Encounters/Data/Encounters4.cs
> Update Gen 4 trade min levels

- README.md
Since SWSH launch: Shiny sprites have been added, and Form was put on a separate FlowLayoutPanel rather than right next to Friendship. Now it's all up-to-date!
> Update README.md screenshot

- PKHeX.Core/Saves/Access/SaveBlockAccessor8SWSH.cs
Nothing special. Just found it and figured why not add it.
> Add another SWSH block

- PKHeX.Core/Resources/text/de/text_Ribbons_de.txt
- PKHeX.Core/Resources/text/ko/text_Ribbons_ko.txt
> Fixes files

- PKHeX.Core/Legality/Encounters/Data/Encounters8NestDist.cs
> Add Gigantamax Meowth Distribution Raids

- PKHeX.Core/Saves/Substructures/Gen7/GP1.cs
Allows for same species summaries to be properly aligned and feeds my Meltan addiction :)
> Pretty up GP1 summary/filename

- PKHeX.Core/PKM/Shared/IDynamaxLevel.cs
Probably easier to blacklist this way?
> Unblock IoA Mons Auto Dynamax

- PKHeX.Core/Saves/Access/SaveBlockAccessor8SWSH.cs
Found these pretty useful blocks for IoA. I'll maybe look into Restricted Sparring data in the next week or so if no one else does by then.
> New SWSH Block Data

- PKHeX.Core/Saves/Access/SaveBlockAccessor8SWSH.cs
Wanted to post this yesterday, but I was busy.
> Added new SWSH blocks

- PKHeX.Core/Saves/Substructures/Gen8/TrainerCard8.cs
> Add MomSkin to League Card

- PKHeX.Core/Legality/Tables/Tables7b.cs
> Unban GO Shiny Bellsprout

- PKHeX.WinForms/Subforms/KChart.Designer.cs
- PKHeX.WinForms/Subforms/KChart.cs
> Add Catch Rate to KChart

- PKHeX.Core/PKM/Util/SpeciesName.cs
Mauvais œuf, je le réparerai. Bon appétit!
Fixes Gen 4 edge case reported by Taya on Discord.
> Gen 4 French Egg Fix

- PKHeX.WinForms/Subforms/Save Editors/Gen4/SAV_Underground.Designer.cs
Makes it match other forms more.
- Form is now resizable
- Form now opens CenterParent rather than WindowsDefault
> Update Underground Editor UI

- PKHeX.Core/Legality/Encounters/Data/Encounters1.cs
- PKHeX.Core/Legality/Encounters/EncounterStatic/EncounterStatic1E.cs
Merged Stadium Psyduck OTs and added Yoshira Mew to Gen 1 event database.
> Changed es1e to allow multi-OT

- PKHeX.Core/Legality/Tables/Tables7b.cs
> Unban GO Shiny Vulpix

- PKHeX.Core/Legality/Encounters/Data/Encounters8.cs
> Static Encounters Update

- PKHeX.Core/Saves/Access/SaveBlockAccessor8SWSH.cs
> Added more Tundra Blocks

- PKHeX.Core/Saves/Access/SaveBlockAccessor8SWSH.cs
Should be ``6F669A35    WK_EV_R2_CHIKA_LEGEND_SAVE_01``
> Fix incorrect offset for first Max Lair saved note

- PKHeX.WinForms/Controls/PKM Editor/PKMEditor.cs
Was only updating based on Stat Nature?
> Fix Stat Tooltips

- PKHeX.Core/Saves/Substructures/Gen8/TrainerCard8.cs
> Add CrownDex complete to Trainer Card

- PKHeX.Core/Legality/Areas/EncounterArea8.cs
- PKHeX.Core/Legality/Encounters/Data/Encounters8.cs
~~Leaving this up to collect crossover encounters.~~
Done for now.
> Add crossover and static encounters for CT

- PKHeX.Core/Resources/text/script/flags_hgss_en.txt
- PKHeX.Core/Resources/text/script/flags_hgss_es.txt
- PKHeX.Core/Resources/text/script/flags_hgss_ja.txt
- PKHeX.Core/Resources/text/script/flags_hgss_ko.txt
- PKHeX.Core/Resources/text/script/flags_hgss_zh.txt
> Added Bill's Eevee Gift and Route 36 Sudowoodo flags in HGSS

- PKHeX.Core/Legality/Encounters/Data/Encounters1.cs
Fixes issue: https://github.com/kwsch/PKHeX/issues/3083
> Fix issue #3083

- PKHeX.Core/Resources/text/script/flags_pt_en.txt
- PKHeX.Core/Resources/text/script/flags_pt_ja.txt
- PKHeX.Core/Resources/text/script/flags_pt_zh.txt
List of event flag in this pr:
Porygon(Veilstone City)
Eevee(Hearthome City)
Unlocked Bebe's PC
> Add some event flag of gift pokemon for Platinum version

- PKHeX.WinForms/Controls/PKM Editor/TrainerID.cs
Should fix https://github.com/kwsch/PKHeX/issues/3087.
> Fix parsing SID error

- PKHeX.Core/Saves/Substructures/Gen8/TrainerCard8.cs
#3086 
Was only partially addressed -- it was only done for Title Screen and not League Card too.
> Properly set empty slots to Trainer Card

- PKHeX.Core/Resources/text/script/flags_dp_en.txt
- PKHeX.Core/Resources/text/script/flags_rs_en.txt
> Add running shoes for DP + merge 1 RS event flag

- PKHeX.Core/Resources/text/script/const_dp_en.txt
- PKHeX.Core/Resources/text/script/const_dp_es.txt
- PKHeX.Core/Resources/text/script/const_pt_en.txt
- PKHeX.Core/Resources/text/script/const_pt_es.txt
Just doing English and Spanish since Korean and Chinese already had these.
> Update DPPt Starter event constants

- PKHeX.Core/Resources/text/script/flags_dp_en.txt
- PKHeX.Core/Resources/text/script/flags_frlg_en.txt
- PKHeX.Core/Resources/text/script/flags_rs_en.txt
> Added a few RS, FRLG and DP Event Flags

- PKHeX.Core/Resources/text/script/flags_dp_en.txt
- PKHeX.Core/Resources/text/script/flags_dp_es.txt
- PKHeX.Core/Resources/text/script/flags_dp_ja.txt
- PKHeX.Core/Resources/text/script/flags_dp_ko.txt
- PKHeX.Core/Resources/text/script/flags_dp_zh.txt
- PKHeX.Core/Resources/text/script/flags_frlg_es.txt
- PKHeX.Core/Resources/text/script/flags_frlg_zh.txt
- PKHeX.Core/Resources/text/script/flags_rs_es.txt
- PKHeX.Core/Resources/text/script/flags_rs_zh.txt
I also updated the Spanish FRLG translation file with 2 Flags.
> Added Bebe's PC Event Flag for DP + Update Gen 3 & 4 translations

- PKHeX.Core/Resources/text/script/const_c_en.txt
- PKHeX.Core/Resources/text/script/const_gs_en.txt
- PKHeX.Core/Resources/text/script/flags_c_en.txt
- PKHeX.Core/Resources/text/script/flags_c_es.txt
- PKHeX.Core/Resources/text/script/flags_c_ja.txt
- PKHeX.Core/Resources/text/script/flags_c_zh.txt
- PKHeX.Core/Resources/text/script/flags_gs_en.txt
- PKHeX.Core/Resources/text/script/flags_gs_es.txt
- PKHeX.Core/Resources/text/script/flags_gs_ja.txt
- PKHeX.Core/Resources/text/script/flags_gs_ko.txt
- PKHeX.Core/Resources/text/script/flags_gs_zh.txt
> Add Gen 2 Event Constants and Legendary Beasts Flag

- PKHeX.Core/Resources/text/script/const_c_es.txt
- PKHeX.Core/Resources/text/script/const_e_es.txt
- PKHeX.Core/Resources/text/script/const_hgss_es.txt
- PKHeX.Core/Resources/text/script/const_pt_es.txt
- PKHeX.Core/Resources/text/script/const_usum_es.txt
- PKHeX.Core/Resources/text/script/flags_b2w2_es.txt
- PKHeX.Core/Resources/text/script/flags_c_es.txt
- PKHeX.Core/Resources/text/script/flags_oras_es.txt
- PKHeX.Core/Resources/text/script/flags_usum_es.txt
Hello i'm Matias and this is my colaborations to this proect:
I've working in a updated of the Spanish texts in the Resources folder. There were some texts that were still in English so I decided to translate them, there are still some translations pending if my collaboration is accepted I will continue working on those translations. If you have any suggestions I am at your disposal to listen to them
> Edit: The Spanish texts in the Resources folder have been updated.

- PKHeX.Core/Resources/text/script/flags_c_en.txt
- PKHeX.Core/Resources/text/script/flags_c_es.txt
- PKHeX.Core/Resources/text/script/flags_c_ja.txt
- PKHeX.Core/Resources/text/script/flags_c_zh.txt
- PKHeX.Core/Resources/text/script/flags_gs_en.txt
- PKHeX.Core/Resources/text/script/flags_gs_es.txt
- PKHeX.Core/Resources/text/script/flags_gs_ja.txt
- PKHeX.Core/Resources/text/script/flags_gs_ko.txt
- PKHeX.Core/Resources/text/script/flags_gs_zh.txt
Also, added Spanish Crystal translations done from https://github.com/kwsch/PKHeX/commit/4bdff06145c6c24715ad63d6583def1c9ccd58c9 to Spanish GS.
> Corrected GSC Sudowoodo Event Flag

- PKHeX.Core/Resources/text/gen3/text_ItemsG3Colosseum_de.txt
- PKHeX.Core/Resources/text/gen3/text_ItemsG3XD_de.txt
I translated the Colosseum and XD exclusive item files to German.
> Colosseum and XD German Item Names

- PKHeX.WinForms/MainWindow/Main.Designer.cs
- PKHeX.WinForms/MainWindow/Main.cs
I've added a tool tip to the legal PictureBox to help guide users in getting more information when they are getting the invalid image.
> Added a tool tip to the legal PictureBox to better help new users.

- PKHeX.Core/Resources/text/script/gen3/flags_e_en.txt
added a lot of flags to emerald
> added a lot of flags to emerald

- PKHeX.Core/Resources/text/script/gen8/work_bdsp_en.txt
- PKHeX.WinForms/Subforms/Save Editors/Gen8/SAV_FlagWork8b.Designer.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen8/SAV_FlagWork8b.cs
> Added named constant for BDSP swarms

- PKHeX.Core/Saves/Access/SaveBlockAccessor8LA.cs
For the Starter and a minigame high score.
Edit: Also included Lost & Found records and its object data.
> Add Legends: Arceus blocks

- .gitignore
- Added Jetbrains files extensions
- Added history files for VS and VSC
- Minor update in Python
> Added several files in gitignore

- .github/README-zh.md
- README.md
Add Simplified Chinese version of "README" file
> Add README-zh.md

- PKHeX.Core/Util/MessageStrings.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen5/SAV_Misc5.Designer.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen5/SAV_Misc5.cs
-- BW: Dump/import black city/white forest data from each other.
-- BW: Reset thundurus/tornadus flags so they can be roaming again by visiting the cabin at route 7.
Reset this flag and switch your BW version with the same save file, you can catch the other pokemon that's limited to a sole version.
> Gen 5 enhancements.

- Directory.Build.props
For future SysBot's single-file build time output.
> Add build timestamp.

- PKHeX.Core/Saves/Substructures/Gen3/Events/MysteryEvent3RS.cs
- PKHeX.Core/Saves/Substructures/Gen3/Events/WonderCard3.cs
> Fixed offset for MysteryEvent3RS checksum

- PKHeX.Core/Saves/SAV8SWSH.cs
- PKHeX.Core/Saves/Substructures/Gen8/SWSH/FashionUnlock8.cs
Also document what the relevant regions are as constants.
> Expose FashionUnlock8 From SAV8SWSH

- PKHeX.WinForms/Subforms/Save Editors/Gen9/SAV_Trainer9.Designer.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen9/SAV_Trainer9.cs
> Add Game Start Time Editor For Scarlet and Violet

- PKHeX.Core/Resources/text/script/gen5/flags_bw_en.txt
- PKHeX.Core/Resources/text/script/gen5/flags_bw_es.txt
- PKHeX.Core/Resources/text/script/gen5/flags_bw_fr.txt
- PKHeX.Core/Resources/text/script/gen5/flags_bw_ja.txt
- PKHeX.Core/Resources/text/script/gen5/flags_bw_ko.txt
- PKHeX.Core/Resources/text/script/gen5/flags_bw_zh.txt
- PKHeX.Core/Resources/text/script/gen5/flags_bw_zh2.txt
I added the flags to the other translations in English so that someone more well versed in the respective language can add a proper translation.
> Add battle subway trophy flags (BW)

- PKHeX.Core/Legality/Encounters/Templates/Gen3/XD/EncounterTrade3XD.cs
- PKHeX.Core/Legality/Encounters/Templates/Gen6/EncounterStatic6.cs
- PKHeX.Core/Legality/Encounters/Templates/Gen8/EncounterTrade8.cs
- PKHeX.Core/Legality/Encounters/Templates/Gen9/EncounterDist9.cs
- PKHeX.Core/Legality/Encounters/Templates/Gen9/EncounterFixed9.cs
- PKHeX.Core/Legality/Encounters/Templates/Gen9/EncounterMight9.cs
- PKHeX.Core/Legality/Encounters/Templates/Gen9/EncounterStatic9.cs
- PKHeX.Core/Legality/Encounters/Templates/Gen9/EncounterTera9.cs
Following the pattern that I noticed with the last time I reported a similar issue I adjusted a few more ConvertToPKM methods that had similar issues to the previous tweaks.
> - misc template -> pk tweaks

- PKHeX.Core/Legality/Encounters/Templates/Gen4/EncounterTrade4RanchGift.cs
- PKHeX.Core/Legality/Encounters/Templates/Gen7/EncounterStatic7.cs
- PKHeX.Core/Legality/Encounters/Templates/Gen8a/EncounterStatic8a.cs
- Fateful Encounter check for some static encounters like Darkrai, Shaymin, Phione etc.
> - EncounterStatic8a tweak

- PKHeX.Core/Saves/Util/SaveUtil.cs
Reference: https://projectpokemon.org/home/forums/topic/63895-file-size-too-large/
> Additional G9 DLC Save Sizes

- PKHeX.Core/Saves/Util/SaveUtil.cs
Issue reported in the forum:
https://projectpokemon.org/home/forums/topic/64137-sv-202-save-file-cant-open/
> Add one more SV DLC1 save size

- PKHeX.Core/Saves/Substructures/Gen6/Encount6.cs
- PKHeX.WinForms/Controls/SAV Editor/SAVEditor.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen3/SAV_Roamer3.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen6/SAV_Roamer6.Designer.cs
- PKHeX.WinForms/Subforms/Save Editors/Gen6/SAV_Roamer6.cs
- Add GUI For XY Roamer
- Change Encout6 to use Memory since Slice made a copy which meant that changing values on Roamer6 didn't persist back to the underlying data without reassigning Encount.
> Add GUI For XY Roamer

- PKHeX.Core/Saves/SAV1.cs
- PKHeX.Core/Saves/Substructures/Gen12/SAV1Offsets.cs
Although a little more primitive, it does have an Event Work area, controlling some interesting stuff like Viridian Mart state, Rival battles in Route 22 and the Rival battle in SS Anne 2F.
The offsets for both international and Japanese versions are provided.
Implementation was based on SAV2, which does not do any extra checks, like event flags does, and may edit data beyond EventWorkCount.
> SAV1 can implement IEventWorkArray<byte>

- PKHeX.Core/Saves/Access/SaveBlockAccessor9SV.cs
I've added names for some common blocks that are useful for my plugin FlagsEditorEX.
I've put the definitions at the same block types.
Feel free to suggest better names.
> Naming useful SV blocks

- PKHeX.WinForms/Controls/SAV Editor/SAVEditor.Designer.cs
- PKHeX.WinForms/Controls/SAV Editor/SAVEditor.cs
Given that the raid button is used for both games, consolidate the buttons for DLC raids.
> Consolidate DLC Raid Buttons

- PKHeX.Core/Saves/Access/ISaveBlock7b.cs
- PKHeX.Core/Saves/Access/SaveBlockAccessor7b.cs
- PKHeX.Core/Saves/SAV7b.cs
- PKHeX.Core/Saves/Substructures/Gen7/LGPE/PlayerGeoLocation7b.cs
Adventure Begin Time apparently in the Player Geo Location data.
> Add LGPE Adventure Begin Date

- PKHeX.Core/Saves/Substructures/Time/Epoch0000DateTime.cs
- PKHeX.Core/Saves/Substructures/Time/Epoch1900DateTimeValue.cs
- PKHeX.Core/Saves/Substructures/Time/EpochDateTime.cs
Fix some of the minor things I missed in #4208
> Minor Changes To EpochDateTime

- PKHeX.Core/Saves/Substructures/Gen3/SecretBase3.cs
- PKHeX.Core/Saves/Substructures/Gen3/SecretBase3PKM.cs
- PKHeX.Core/Saves/Substructures/Gen3/SecretBase3Team.cs
Some data was read from wrong offsets.
> Fixed SecretBase3Team

- PKHeX.Core/MysteryGifts/WA8.cs
- PKHeX.Core/MysteryGifts/WB7.cs
- PKHeX.Core/MysteryGifts/WB8.cs
- PKHeX.Core/MysteryGifts/WC8.cs
- PKHeX.Core/MysteryGifts/WC9.cs
Off by one, CHT OT gets skipped
> Fix CHT OriginalTrainerName setter for crafted WCs

- PKHeX.Core/Resources/config/battle_fr.json
Minor improvements to the pretty good localization.
> improve fr translation
